--------------------------------------------------------------------------------
-- General
_G.DOTA_MONSTER_TEAM_NUMBER = 1
-- Custom Damage Flags
_G.DOTA_CUSTOM_DAMAGE_FLAG_NO_ADDITIONAL_EFFECT = 1048576

--Data Type
_G.INT_TYPE = 1
_G.FLOAT_TYPE = 2

--Custom heal_flag
_G.DOTA_CUSTOM_HEAL_FLAG_NONE = 0   --没有
_G.DOTA_CUSTOM_HEAL_FLAG_NO_FUNCTION_HEAL = 1   --不触发function 发出治疗
_G.DOTA_CUSTOM_HEAL_FLAG_NO_FUNCTION_HEALRECEIVE = 2   --不触发function 受到治疗


--Custom Summon flag
_G.DOTA_CUSTOM_SUMMON_FLAG_NONE = 0
_G.DOTA_CUSTOM_SUMMON_FLAG_NO_FUNCTION_CALLED = 1  --不触发事件
_G.DOTA_CUSTOM_SUMMON_FLAG_NO_CALL_SUMMON = 2  --不触发召唤事件
_G.DOTA_CUSTOM_SUMMON_FLAG_NO_CALL_SUMMON_FINISHED = 4  --不触发召唤完成事件
-- --MODIFIER_STATE
-- _G.MODIFIER_STATE_INCOMING_DAMAGE_REDUCE_DISABLED = 50  --伤害减免百分比无效化



--Gift
_G.DOTA_CUSTOM_GiftIndex_None = 0
_G.DOTA_CUSTOM_GiftIndex_1 = 1  
_G.DOTA_CUSTOM_GiftIndex_FIRSTHERO = 2  
_G.DOTA_CUSTOM_GiftIndex_SECONDHERO = 4
_G.DOTA_CUSTOM_GiftIndex_BETA = 8
_G.DOTA_CUSTOM_GiftIndex_NICEFIX = 16
_G.DOTA_CUSTOM_GiftIndex_NICEFIX2 = 32
_G.DOTA_CUSTOM_GiftIndex_NICEFIX3 = 64
_G.DOTA_CUSTOM_GiftIndex_NICEFIX4 = 128
_G.DOTA_CUSTOM_GiftIndex_NICEFIX5 = 256
_G.DOTA_CUSTOM_GiftIndex_NICEFIX6 = 512
_G.DOTA_CUSTOM_GiftIndex_NICEFIX7 = 1024
_G.DOTA_CUSTOM_GiftIndex_NICEFIX8 = 2048
_G.DOTA_CUSTOM_GiftIndex_NICEFIX9 = 4096
_G.DOTA_CUSTOM_GiftIndex_NICEFIX10 = 8192
_G.DOTA_CUSTOM_GiftIndex_NICEFIX11 = 16384
_G.DOTA_CUSTOM_GiftIndex_NICEFIX12 = 32768
_G.DOTA_CUSTOM_GiftIndex_NICEFIX13 = 65536
_G.DOTA_CUSTOM_GiftIndex_NICEFIX14 = 131072
_G.DOTA_CUSTOM_GiftIndex_NICEFIX15 = 262144
_G.DOTA_CUSTOM_GiftIndex_NICEFIX16 = 524288
_G.DOTA_CUSTOM_GiftIndex_NICEFIX17 = 1048576
_G.DOTA_CUSTOM_GiftIndex_NICEFIX18 = 2097152
_G.DOTA_CUSTOM_GiftIndex_NICEFIX19 = 4194304



--COST_TYPE
_G.TYPE_COST_Aurum = 1
_G.TYPE_COST_Platinum = 2
_G.TYPE_COST_EXP = 3


--SHOP TYPE
_G.TYPE_BUY_EXP = 1
_G.TYPE_BUY_Spell_Book = 2
_G.TYPE_BUY_Aurum = 3
_G.TYPE_BUY_CORE = 4
_G.TYPE_BUY_ParticleEffect = 5
_G.TYPE_BUY_Rune = 6


--ABILITY_ELEMENT_TYPE
_G.ABILITY_ELEMENT_TYPE_NONE = 0       --无属性
_G.ABILITY_ELEMENT_TYPE_FIRE = 1       --火属性
_G.ABILITY_ELEMENT_TYPE_ICE = 2        --冰属性
_G.ABILITY_ELEMENT_TYPE_LIGHTNING = 4  --雷属性
_G.ABILITY_ELEMENT_TYPE_LIGHT = 8      --光属性
_G.ABILITY_ELEMENT_TYPE_DARK = 16      --暗属性


--伤害颜色
_G.DAMAGE_COLOR_NORMAL = Vector(255,255,255)
_G.DAMAGE_COLOR_PHYSICAL = Vector(255,100,100)
_G.DAMAGE_COLOR_MAGICAL = Vector(0,150,255)
_G.DAMAGE_COLOR_PURE = Vector(255,255,100)

_G.DAMAGE_TAKE_COLOR_NORMAL = Vector(200,100,100)
-- _G.DAMAGE_TAKE_COLOR_PHYSICAL = Vector(255,144,144)
-- _G.DAMAGE_TAKE_COLOR_MAGICAL = Vector(145,236,255)
-- _G.DAMAGE_TAKE_COLOR_PURE = Vector(255,253,143)



_G.COOLDOWN_REDUCTION_MAX_VALUE = 60  --冷却缩减最大值

_G.Chaotic_Era_Spell_Require_Index = 0.9  --解锁乱纪元所需技能个数的乘数

_G.Enable_Chaotic_Era = true  --是否开启乱纪元模式
if IsInToolsMode() then
	Enable_Chaotic_Era = true
end

-- 平衡常数
Strength_As_Health_Regen = 0.08
Intelligence_As_Mana_Regen = 0.05
Agility_As_Armor = 0.1

-- 在最终加成需要再去掉这个数值回正 因为SetCustomAttributeDerivedStatValue没用
Strength_As_Health_Regen_Origin = 0.1
Intelligence_As_Mana_Regen_Origin = 0.05



-- 技能类型
ABILITY_TYPE_GENERAL_SHOP = 1
ABILITY_TYPE_CHAOTIC_ERA_SPECIAL = 2
ABILITY_TYPE_OTHER = 4



-- 商店类型
Game_Shop_Type_Normal = 1
Game_Shop_Type_ChaoticEra = 2


-- 自定义事件
MODIFIER_EVENT_ON_Wave_Start = MODIFIER_FUNCTION_LAST + 1 -- OnSummonned
MODIFIER_EVENT_ON_Wave_End = MODIFIER_EVENT_ON_Wave_Start + 1
MODIFIER_EVENT_ON_CAST_DEFAULT_MOVE = MODIFIER_EVENT_ON_Wave_End + 1
MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK = MODIFIER_EVENT_ON_CAST_DEFAULT_MOVE + 1
MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_LOW_LEVEL= MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK + 1
MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_HIGHT_LEVEL = MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_LOW_LEVEL + 1
MODIFIER_SPECIAL_Temporary_Health_Points = MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_HIGHT_LEVEL + 1
MODIFIER_SPECIAL_Reincarnate = MODIFIER_SPECIAL_Temporary_Health_Points + 1
MODIFIER_SPECIAL_ChaoticEra_GetAdditionalShopItem = MODIFIER_SPECIAL_Reincarnate + 1
MODIFIER_SPECIAL_ChaoticEra_MadifySpawnData= MODIFIER_SPECIAL_ChaoticEra_GetAdditionalShopItem + 1


MODIFIER_EVENT_ON_CRITICAL_STRIKE_TRIGGER = MODIFIER_SPECIAL_ChaoticEra_MadifySpawnData + 1
MODIFIER_EVENT_ON_MODIFIER_APPLIED = MODIFIER_EVENT_ON_CRITICAL_STRIKE_TRIGGER + 1


MODIFIER_EVENT_ON_LEARN_NEW_SPELL = MODIFIER_EVENT_ON_MODIFIER_APPLIED + 1
MODIFIER_EVENT_ON_Sell_SPELL = MODIFIER_EVENT_ON_LEARN_NEW_SPELL + 1
MODIFIER_EVENT_ON_ChaoticEraRoundChange = MODIFIER_EVENT_ON_Sell_SPELL + 1
MODIFIER_EVENT_ON_ChaoticEraMonsterSpawn = MODIFIER_EVENT_ON_ChaoticEraRoundChange + 1
MODIFIER_EVENT_ON_Heal = MODIFIER_EVENT_ON_ChaoticEraMonsterSpawn + 1
MODIFIER_EVENT_ON_Chat= MODIFIER_EVENT_ON_Heal + 1
MODIFIER_EVENT_ON_SUMMON= MODIFIER_EVENT_ON_Chat + 1
--寒霜传送门 这是自定义事件的地方--
MODIFIER_EVENT_ON_DEATH_AGAIN = MODIFIER_EVENT_ON_SUMMON + 1
MODIFIER_EVENT_ON_VITALITY = MODIFIER_EVENT_ON_DEATH_AGAIN + 1
MODIFIER_EVENT_ON_BURNING = MODIFIER_EVENT_ON_VITALITY + 1
MODIFIER_EVENT_ON_FREEZING = MODIFIER_EVENT_ON_BURNING + 1
MODIFIER_EVENT_ON_ELECSHOCKING = MODIFIER_EVENT_ON_FREEZING + 1

MODIFIER_FUNCTION_NAME = {
	[MODIFIER_EVENT_ON_Wave_Start] = "OnWaveStart",
	[MODIFIER_EVENT_ON_Wave_End] = "OnWaveEnd",
	[MODIFIER_EVENT_ON_CAST_DEFAULT_MOVE] = "OnCastDefaultMove",
	[MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK] = "AdvancedGetModifierTotal_ConstantBlock",
	[MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_LOW_LEVEL] = "AdvancedGetModifierTotal_ConstantBlock_LowLevel",
	[MODIFIER_SPECIAL_CALCULATE_TOTAL_CONSTANT_BLOCK_HIGHT_LEVEL] = "AdvancedGetModifierTotal_ConstantBlock_HightLevel",
	[MODIFIER_SPECIAL_Temporary_Health_Points] = "AdvancedGetModifierTemporaryHealth",
	[MODIFIER_SPECIAL_Reincarnate] = "AdvancedGetModifierReincarnate",
	[MODIFIER_SPECIAL_ChaoticEra_GetAdditionalShopItem] = "GetChaoticEraAdditionalShopItem",
	[MODIFIER_SPECIAL_ChaoticEra_MadifySpawnData] = "AdvancedModifyChaoticEraSpwnData",



	[MODIFIER_EVENT_ON_CRITICAL_STRIKE_TRIGGER] = "AdvancedOnCriticalStrikeTrigger",
	[MODIFIER_EVENT_ON_MODIFIER_APPLIED] = "AdvancedOnModifierApplied",
	[MODIFIER_EVENT_ON_LEARN_NEW_SPELL] = "AdvancedOnLearnNewSpell",
	[MODIFIER_EVENT_ON_Sell_SPELL] = "AdvancedOnSellSpell",
	[MODIFIER_EVENT_ON_ChaoticEraRoundChange] = "OnChaoticEraRoundChange",
	[MODIFIER_EVENT_ON_ChaoticEraMonsterSpawn] = "AdvancedOnChaoticEraMonsterSpawn",
	[MODIFIER_EVENT_ON_Heal] = "AdvancedOnHeal",
	[MODIFIER_EVENT_ON_Chat] = "AdvancedOnChat",
	[MODIFIER_EVENT_ON_SUMMON] = "AdvancedOnSummon",
	[MODIFIER_EVENT_ON_DEATH_AGAIN] = "AdvancedOnDeathAgain",
	[MODIFIER_EVENT_ON_VITALITY] = "AdvancedOnVitality",
	[MODIFIER_EVENT_ON_BURNING] = "AdvancedOnBurning",
	[MODIFIER_EVENT_ON_FREEZING] = "AdvancedOnFreezing",
	[MODIFIER_EVENT_ON_ELECSHOCKING] = "AdvancedOnElecshocking",


	
}






-- 基础属性
HeroBase_Vision_Day = 3000
HeroBase_Vision_Night = 2000





-- 毒相关
POISON_TICKTIME = 1
POISON_DURATION = 10
MAX_POISON_STACK = 1000000000

-- 背刺相关

-- 点燃相关
BURNING_TICKTIME = 1
BURNING_DURATION = 5
MAX_BURNING_STACK = 1000000000

-- 冻伤相关
FREEZING_TICKTIME = 1
FREEZING_DURATION = 10
MAX_FREEZING_STACK = 1000000000

-- 感电相关
ELECSHOCKING_TICKTIME = 1
MAX_ELECSHOCKING_STACK = 3000
