GameUI.CustomUIConfig().ChaoticEra_MapEffect = {
	"diff_1": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diff_1.png",
		"weight": 10,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"hp": 100,
			"atk": 100,
			"rune": 100,
			"boss_rune": 10,
		},
	},
	"diff_2": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diff_2.png",
		"weight": 20,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"hp": 250,
			"atk": 200,
			"rune": 260,
			"boss_rune": 30,
		},
	},
	"diff_3": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diff_3.png",
		"weight": 30,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"hp": 600,
			"atk": 275,
			"rune": 520,
			"boss_rune": 60,
		},
	},
	"diff_4": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diff_4.png",
		"weight": 40,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"hp": 1000,
			"atk": 350,
			"rune": 750,
			"boss_rune": 100,
		},
	},
	"diff_5": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diff_5.png",
		"weight": 50,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"hp": 1800,
			"atk": 500,
			"rune": 1250,
			"boss_rune": 190,
		},
	},
	"diviners_portent": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/diviners_portent.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 5,
			"value2": 35,
			"value3": 1,
			"boss_rune": 13,
		},
		"AbilityValues_Middle": {
			"value1": 5,
			"value2": 70,
			"value3": 1,
			"boss_rune": 16,
		},
		"AbilityValues_Advanced": {
			"value1": 5,
			"value2": 110,
			"value3": 1,
			"boss_rune": 19,
		},
	},
	"super_elite": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/super_elite.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Middle": {
			"rune": 60,
			"boss_rune": 20,
		},
	},
	"queens_vanguard_army": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/queens_vanguard_army.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 4,
			"value2": 140,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 4,
			"value2": 200,
			"boss_rune": 20,
		},
		"AbilityValues_Advanced": {
			"value1": 4,
			"value2": 350,
			"boss_rune": 24,
		},
	},
	"horn_of_the_alhpa": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/horn_of_the_alhpa.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 1,
			"value2": 185,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 1,
			"value2": 480,
			"boss_rune": 20,
		},
		"AbilityValues_Advanced": {
			"value1": 1,
			"value2": 840,
			"boss_rune": 24,
		},
	},
	"continuous_stream_of_trees": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/continuous_stream_of_trees.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 2,
			"value2": 135,
			"value3": 224,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 2,
			"value2": 192,
			"value3": 320,
			"boss_rune": 20,
		},
		"AbilityValues_Advanced": {
			"value1": 2,
			"value2": 336,
			"value3": 560,
			"boss_rune": 24,
		},
	},
	"undeath_legion": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/undeath_legion.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 1,
			"value2": 170,
			"value3": 540,
			"count": 3,
			"value4": 3,
			"boss_rune": 13,
		},
	},
	"iron_fog_goldmine": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/iron_fog_goldmine.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 10,
			"value2": 16,
			"boss_rune": 10,
		},
		"AbilityValues_Middle": {
			"value1": 15,
			"value2": 40,
			"boss_rune": 13,
		},
	},
	"smothering_tithe": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/smothering_tithe.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"gold": 3000,
			"interval": 30,
			"back": 20,
			"value2": 4,
			"boss_rune": 10,
			"bonus": 1,
			"index": 160,
		},
	},
	"greedy": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/greedy.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 20,
			"value2": 16,
			"boss_rune": 10,
		},
		"AbilityValues_Middle": {
			"value1": 40,
			"value2": 40,
			"boss_rune": 13,
		},
	},
	"be_careful_at_night": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/be_careful_at_night.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 21,
			"value2": 26,
			"value3": 200,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 51,
			"value2": 64,
			"value3": 400,
			"boss_rune": 20,
		},
		"AbilityValues_Advanced": {
			"value1": 77,
			"value2": 96,
			"value3": 600,
			"boss_rune": 24,
		},
	},
	"be_careful_at_night_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/be_careful_at_night_hard.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 51,
			"value2": 64,
			"value3": 400,
			"value4": 10,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 77,
			"value2": 96,
			"value3": 600,
			"value4": 20,
			"boss_rune": 24,
		},
		"AbilityValues_Advanced": {
			"value1": 128,
			"value2": 160,
			"value3": 800,
			"value4": 30,
			"boss_rune": 28,
		},
	},
	"imprint_of_nevermore": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/imprint_of_nevermore.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 30,
			"value2": 10,
			"value3": 26,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 60,
			"value2": 15,
			"value3": 64,
			"boss_rune": 20,
		},
	},
	"crazy_surf": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/crazy_surf.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 26,
			"value2": 20,
			"boss_rune": 16,
		},
		"AbilityValues_Middle": {
			"value1": 64,
			"value2": 40,
			"boss_rune": 20,
		},
		"AbilityValues_Advanced": {
			"value1": 96,
			"value2": 49,
			"boss_rune": 24,
		},
	},
	"crazy_surf_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/crazy_surf_hard.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 64,
			"value2": 40,
			"value3": 30,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 96,
			"value2": 49,
			"value3": 40,
			"boss_rune": 24,
		},
		"AbilityValues_Advanced": {
			"value1": 160,
			"value2": 62,
			"value3": 50,
			"boss_rune": 28,
		},
	},
	"more_deadly": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/more_deadly.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 32,
			"value2": 32,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 80,
			"value2": 80,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 120,
			"value2": 120,
			"boss_rune": 30,
		},
	},
	"more_deadly_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/more_deadly_hard.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 80,
			"value2": 80,
			"value3": 15,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 120,
			"value2": 120,
			"value3": 25,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 200,
			"value2": 200,
			"value3": 35,
			"boss_rune": 35,
		},
	},
	"planar_bridge": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/planar_bridge.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 3,
			"value2": 32,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 6,
			"value2": 80,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 9,
			"value2": 120,
			"boss_rune": 30,
		},
	},
	"planar_bridge_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/planar_bridge_hard.png",
		"weight": 100,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 6,
			"value2": 80,
			"value3": 8,
			"value4": 8,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 9,
			"value2": 120,
			"value3": 13,
			"value4": 13,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 12,
			"value2": 200,
			"value3": 18,
			"value4": 18,
			"boss_rune": 35,
		},
	},
	"weirding_wood": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/weirding_wood.png",
		"weight": 65,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 40,
			"value2": 40,
			"value3": 40,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"boss_rune": 30,
		},
	},
	"weirding_wood_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/weirding_wood_hard.png",
		"weight": 35,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"value4": 15,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"value4": 25,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 250,
			"value2": 250,
			"value3": 250,
			"value4": 35,
			"boss_rune": 35,
		},
	},
	"chaos_coming": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/chaos_coming.png",
		"weight": 65,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 40,
			"value2": 40,
			"value3": 40,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"boss_rune": 30,
		},
	},
	"chaos_coming_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/chaos_coming_hard.png",
		"weight": 35,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"value4": 15,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"value4": 25,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 250,
			"value2": 250,
			"value3": 250,
			"value4": 35,
			"boss_rune": 35,
		},
	},
	"element_coming": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/element_coming.png",
		"weight": 65,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 40,
			"value2": 40,
			"value3": 40,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"boss_rune": 30,
		},
	},
	"element_coming_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/element_coming_hard.png",
		"weight": 35,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"value4": 15,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"value4": 25,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 250,
			"value2": 250,
			"value3": 250,
			"value4": 35,
			"boss_rune": 35,
		},
	},
	"nega_coming": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/nega_coming.png",
		"weight": 65,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 40,
			"value2": 40,
			"value3": 40,
			"boss_rune": 20,
		},
		"AbilityValues_Middle": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"boss_rune": 25,
		},
		"AbilityValues_Advanced": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"boss_rune": 30,
		},
	},
	"nega_coming_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/nega_coming_hard.png",
		"weight": 35,
		"disable_primary": 1,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 100,
			"value2": 100,
			"value3": 100,
			"value4": 15,
			"boss_rune": 25,
		},
		"AbilityValues_Middle": {
			"value1": 150,
			"value2": 150,
			"value3": 150,
			"value4": 25,
			"boss_rune": 30,
		},
		"AbilityValues_Advanced": {
			"value1": 250,
			"value2": 250,
			"value3": 250,
			"value4": 35,
			"boss_rune": 35,
		},
	},
	"heroic_obelisk": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/heroic_obelisk.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 8,
			"value2": 25,
			"value3": 1,
			" ": 1,
			"value5": 40,
			"value6": 120,
			"value7": 30,
		},
		"AbilityValues_Middle": {
			"value1": 8,
			"value2": 20,
			"value3": 1,
			"value4": 1,
			"value5": 60,
			"value6": 120,
			"value7": 40,
		},
		"AbilityValues_Advanced": {
			"value1": 9,
			"value2": 15,
			"value3": 1,
			"value4": 1,
			"value5": 70,
			"value6": 120,
			"value7": 50,
		},
	},
	"curse_contract": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/curse_contract.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 20,
			"value2": 25,
			"value3": 60,
			"value4": 1,
			"value5": 3,
		},
		"AbilityValues_Middle": {
			"value1": 30,
			"value2": 25,
			"value3": 80,
			"value4": 1,
			"value5": 4,
		},
		"AbilityValues_Advanced": {
			"value1": 45,
			"value2": 25,
			"value3": 110,
			"value4": 1,
			"value5": 5,
		},
	},
	"death_aura": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/death_aura.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 20,
			"value2": 0.003,
			"value3": 4,
		},
		"AbilityValues_Middle": {
			"value1": 35,
			"value2": 0.005,
			"value3": 4,
		},
		"AbilityValues_Advanced": {
			"value1": 60,
			"value2": 0.007,
			"value3": 4,
		},
	},
	"undeath_legion_hard": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/undeath_legion_hard.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 1,
			"value2": 170,
			"value3": 540,
			"count": 3,
			"value4": 3,
		},
		"AbilityValues_Middle": {
			"value1": 1,
			"value2": 240,
			"value3": 1320,
			"count": 4,
			"value4": 4,
		},
		"AbilityValues_Advanced": {
			"value1": 1,
			"value2": 350,
			"value3": 2100,
			"count": 4,
		},
	},
	"ritual_of_summoning": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/ritual_of_summoning.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
	},
	"hell_lava_golem": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/hell_lava_golem.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"wave": 10,
			"value1": 100,
			"value2": 150,
			"value3": 50,
			"value4": 50,
		},
		"AbilityValues_Middle": {
			"wave": 10,
			"value1": 150,
			"value2": 200,
			"value3": 50,
			"value4": 50,
		},
		"AbilityValues_Advanced": {
			"wave": 10,
			"value1": 230,
			"value2": 250,
			"value3": 50,
			"value4": 50,
		},
	},
	"raphaels_hospitality": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/raphaels_hospitality.png",
		"weight": 0,
		"disable_primary": 1,
		"disable_middle": 1,
		"disable_advanced": 0,
		"AbilityValues_Advanced": {
			"value1": 6,
			"value2": 2,
		},
	},
	"destiny_fade": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/destiny_fade.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 12,
		},
	},
	"training_center": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/training_center.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
	},
	"immortal_ceremony": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/immortal_ceremony.png",
		"weight": 0,
		"disable_primary": 1,
		"disable_middle": 1,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 20,
			"value2": 15,
			"value3": "",
		},
		"AbilityValues_Middle": {
			"value1": 40,
			"value2": 30,
			"value3": "",
		},
		"AbilityValues_Advanced": {
			"value1": 60,
			"value2": 60,
			"value3": "",
		},
	},
	"iron_fog_goldmine_easy": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/iron_fog_goldmine_easy.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 1,
		"AbilityValues_Primary": {
			"value1": 16,
			"value2": 25.6,
			"value3": 5,
		},
		"AbilityValues_Middle": {
			"value1": 24,
			"value2": 64,
			"value3": 10,
		},
		"AbilityValues_Advanced": {
			"value1": 32,
			"value2": 96,
			"value3": 20,
		},
	},
	"super_normal": {
		"image": "file://{images}/custom_game/chaotic_era/hud/game_effect/super_normal.png",
		"weight": 0,
		"disable_primary": 0,
		"disable_middle": 0,
		"disable_advanced": 0,
		"AbilityValues_Primary": {
			"value1": 80,
			"value2": 80,
			"value3": 250,
		},
		"AbilityValues_Middle": {
			"value1": 100,
			"value2": 100,
			"value3": 400,
		},
		"AbilityValues_Advanced": {
			"value1": 120,
			"value2": 120,
			"value3": 550,
		},
	},
};