GameUI.CustomUIConfig().ChaoticEraPotionKV = {
	"hd_potion_healing_1": {
		"level": 1,
		"cost": 100,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 500,
		},
		"texture": "potion/hd_potion_healing_1",
	},
	"hd_potion_healing_2": {
		"level": 2,
		"cost": 200,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 1000,
		},
		"texture": "potion/hd_potion_healing_2",
	},
	"hd_potion_healing_3": {
		"level": 3,
		"cost": 400,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 2000,
		},
		"texture": "potion/hd_potion_healing_3",
	},
	"hd_potion_healing_4": {
		"level": 4,
		"cost": 500,
		"count": 4,
		"weight": 0,
		"type": "regen",
		"AbilityValues": {
			"value1": 4000,
			"value2": 30,
			"duration": 10,
		},
		"texture": "potion/hd_potion_healing_4",
	},
	"hd_potion_healing_5": {
		"level": 5,
		"cost": 700,
		"count": 4,
		"weight": 0,
		"type": "regen",
		"AbilityValues": {
			"value1": 8000,
			"value2": 50,
			"duration": 10,
		},
		"texture": "potion/hd_potion_healing_5",
	},
	"hd_potion_regen_mana_1": {
		"level": 1,
		"cost": 100,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 200,
		},
		"texture": "potion/hd_potion_regen_mana_1",
	},
	"hd_potion_regen_mana_2": {
		"level": 2,
		"cost": 200,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 400,
		},
		"texture": "potion/hd_potion_regen_mana_2",
	},
	"hd_potion_regen_mana_3": {
		"level": 3,
		"cost": 400,
		"count": 2,
		"weight": 500,
		"type": "regen",
		"AbilityValues": {
			"value1": 800,
		},
		"texture": "potion/hd_potion_regen_mana_3",
	},
	"hd_potion_regen_mana_4": {
		"level": 4,
		"cost": 500,
		"count": 4,
		"weight": 0,
		"type": "regen",
		"AbilityValues": {
			"value1": 2400,
			"value2": 30,
			"duration": 10,
		},
		"texture": "potion/hd_potion_regen_mana_4",
	},
	"hd_potion_regen_mana_5": {
		"level": 5,
		"cost": 700,
		"count": 4,
		"weight": 0,
		"type": "regen",
		"AbilityValues": {
			"value1": 4800,
			"value2": 50,
			"duration": 10,
		},
		"texture": "potion/hd_potion_regen_mana_5",
	},
	"hd_potion_arcane_boost_1": {
		"level": 2,
		"cost": 500,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"value1": 15,
			"duration": 180,
		},
		"texture": "potion/hd_potion_arcane_boost_1",
	},
	"hd_potion_lightning_speed_1": {
		"level": 2,
		"cost": 500,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"value1": 125,
			"duration": 180,
		},
		"texture": "potion/hd_potion_lightning_speed_1",
	},
	"hd_potion_colossus_1": {
		"level": 3,
		"cost": 800,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"value1": 90,
			"value2": 20,
			"value3": 35,
			"duration": 150,
		},
		"texture": "potion/hd_potion_colossus_1",
	},
	"hd_potion_hill_giant_strength_1": {
		"level": 4,
		"cost": 1300,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"value1": 40,
			"duration": 200,
		},
		"texture": "potion/hd_potion_hill_giant_strength_1",
	},
	"hd_potion_bloodlust_1": {
		"level": 3,
		"cost": 800,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"removeOnReuse": 1,
		"AbilityValues": {
			"value1": 45,
			"value2": 30,
			"value3": 5000,
			"duration": -1,
		},
		"texture": "potion/hd_potion_bloodlust_1",
	},
	"hd_potion_speed_1": {
		"level": 2,
		"cost": 500,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"bonus_move_speed": 25,
			"bonus_attack_speed": 18,
			"distance": 400,
			"cooldown": 1.5,
			"debuff_duration": 6,
			"duration": 120,
		},
		"texture": "potion/hd_potion_speed_1",
	},
	"hd_potion_permanent_vitality_1": {
		"level": 3,
		"cost": 1500,
		"count": 1,
		"weight": 50,
		"type": "buff",
		"removeOnReuse": 1,
		"AbilityValues": {
			"value1": 25,
			"value2": 150,
			"value3": 10,
			"duration": 60,
		},
		"texture": "potion/hd_potion_permanent_vitality_1",
	},
	"hd_potion_permanent_agility_1": {
		"level": 3,
		"cost": 1500,
		"count": 1,
		"weight": 50,
		"type": "buff",
		"removeOnReuse": 1,
		"AbilityValues": {
			"value1": 25,
			"value2": 150,
			"value3": 10,
			"duration": 60,
		},
		"texture": "potion/hd_potion_permanent_agility_1",
	},
	"hd_potion_permanent_wisdom_1": {
		"level": 3,
		"cost": 1500,
		"count": 1,
		"weight": 50,
		"type": "buff",
		"removeOnReuse": 1,
		"AbilityValues": {
			"value1": 25,
			"value2": 150,
			"value3": 10,
			"duration": 60,
		},
		"texture": "potion/hd_potion_permanent_wisdom_1",
	},
	"hd_potion_fly_1": {
		"level": 3,
		"cost": 1300,
		"count": 1,
		"weight": 0,
		"type": "buff",
		"AbilityValues": {
			"duration": 270,
		},
		"texture": "potion/hd_potion_fly_1",
	},
	"hd_potion_revive_1": {
		"level": 5,
		"cost": 4000,
		"count": 1,
		"weight": 5,
		"type": "buff",
		"AbilityValues": {
			"value1": 4,
			"value2": 1,
			"duration": -1,
		},
		"texture": "potion/hd_potion_revive_1",
	},
};