GameUI.CustomUIConfig().SpellShop_PhysicalKV = {
	"Primary_Starbreaker": {
		"cost": 500,
		"level2_id": "Middle_Starbreaker",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Starbreaker",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Luminosity": {
		"cost": 500,
		"level2_id": "Middle_Luminosity",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Luminosity",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Celestial_Hammer": {
		"associated_spells": "Primary_Converge",
		"cost": 500,
		"level2_id": "Middle_Celestial_Hammer",
		"level2_associated_spells": "Middle_Converge",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Celestial_Hammer",
		"level3_associated_spells": "Advanced_Converge",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Solar_Guardian": {
		"cost": 750,
		"level2_id": "Middle_Solar_Guardian",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Solar_Guardian",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Spear": {
		"cost": 500,
		"level2_id": "Middle_Spear",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Spear",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Gods_Rebuke": {
		"cost": 500,
		"level2_id": "Middle_Gods_Rebuke",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Gods_Rebuke",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Spectral_Dagger": {
		"cost": 500,
		"level2_id": "Middle_Spectral_Dagger",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Spectral_Dagger",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Desolate": {
		"cost": 500,
		"level2_id": "Middle_Desolate",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Desolate",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Haunt": {
		"cost": 500,
		"level2_id": "Middle_Haunt",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Haunt",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Burrow_Strike": {
		"cost": 500,
		"level2_id": "Middle_Burrow_Strike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Burrow_Strike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Sand_Storm": {
		"cost": 500,
		"level2_id": "Middle_Sand_Storm",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Sand_Storm",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Caustic_Finale": {
		"cost": 500,
		"level2_id": "Middle_Caustic_Finale",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Caustic_Finale",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Epicenter": {
		"cost": 500,
		"level2_id": "Middle_Epicenter",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Epicenter",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Storm_Bolt": {
		"cost": 500,
		"level2_id": "Middle_Storm_Bolt",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Storm_Bolt",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Great_Cleave": {
		"cost": 500,
		"level2_id": "Middle_Great_Cleave",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Great_Cleave",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_God_Strength": {
		"cost": 750,
		"level2_id": "Middle_God_Strength",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_God_Strength",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Acid_Sparay": {
		"cost": 500,
		"level2_id": "Middle_Acid_Sparay",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Acid_Sparay",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Warpath": {
		"cost": 500,
		"level2_id": "Middle_Warpath",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Warpath",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Time_Lock": {
		"cost": 500,
		"level2_id": "Middle_Time_Lock",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Time_Lock",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Stifling_Dagger": {
		"cost": 500,
		"level2_id": "Middle_Stifling_Dagger",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Stifling_Dagger",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Phantom_Strike": {
		"cost": 500,
		"level2_id": "Middle_Phantom_Strike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Phantom_Strike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Blur": {
		"cost": 500,
		"level2_id": "Middle_Blur",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Blur",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Coup_De_Grace": {
		"cost": 500,
		"level2_id": "Middle_Coup_De_Grace",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Coup_De_Grace",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Powershot": {
		"cost": 500,
		"level2_id": "Middle_Powershot",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Powershot",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Focus_Fire": {
		"cost": 750,
		"level2_id": "Middle_Focus_Fire",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Focus_Fire",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Unstable_Concoction": {
		"associated_spells": "Primary_Unstable_Concoction_Throw",
		"cost": 500,
		"level2_id": "Middle_Unstable_Concoction",
		"level2_associated_spells": "Middle_Unstable_Concoction_Throw",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Unstable_Concoction",
		"level3_associated_spells": "Advanced_Unstable_Concoction_Throw",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Chemical_Rage": {
		"cost": 500,
		"level2_id": "Middle_Chemical_Rage",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Chemical_Rage",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Battle_Hunger": {
		"cost": 500,
		"level2_id": "Middle_Battle_Hunger",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Battle_Hunger",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Culling_Blade": {
		"cost": 500,
		"level2_id": "Middle_Culling_Blade",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Culling_Blade",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Blade_Fury": {
		"cost": 500,
		"level2_id": "Middle_Blade_Fury",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Blade_Fury",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Blade_Dance": {
		"cost": 500,
		"level2_id": "Middle_Blade_Dance",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Blade_Dance",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Omni_Slash": {
		"cost": 750,
		"level2_id": "Middle_Omni_Slash",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Omni_Slash",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_frostmourne": {
		"cost": 500,
		"level2_id": "Middle_frostmourne",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_frostmourne",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_shapeshift": {
		"cost": 500,
		"level2_id": "Middle_shapeshift",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_shapeshift",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_elder_dragon_form": {
		"cost": 500,
		"level2_id": "Middle_elder_dragon_form",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_elder_dragon_form",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_metamorphosis": {
		"cost": 750,
		"level2_id": "Middle_metamorphosis",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_metamorphosis",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_feast": {
		"cost": 500,
		"level2_id": "Middle_feast",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_feast",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_take_aim": {
		"cost": 500,
		"level2_id": "Middle_take_aim",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_take_aim",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_split_shot": {
		"cost": 500,
		"level2_id": "Middle_split_shot",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_split_shot",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_unleash": {
		"cost": 750,
		"level2_id": "Middle_unleash",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_unleash",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_hoof_stomp": {
		"cost": 500,
		"level2_id": "Middle_hoof_stomp",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_hoof_stomp",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Anchor_Smash": {
		"cost": 500,
		"level2_id": "Middle_Anchor_Smash",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Anchor_Smash",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_overpower": {
		"cost": 500,
		"level2_id": "Middle_overpower",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_overpower",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_frost_arrows": {
		"cost": 500,
		"level2_id": "Middle_frost_arrows",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_frost_arrows",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_marksmanship": {
		"cost": 500,
		"level2_id": "Middle_marksmanship",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_marksmanship",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_unrivaled": {
		"cost": 500,
		"level2_id": "Middle_unrivaled",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_unrivaled",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_hunter_in_the_night": {
		"cost": 500,
		"level2_id": "Middle_hunter_in_the_night",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_hunter_in_the_night",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_quadruple_chop": {
		"cost": 500,
		"level2_id": "Middle_quadruple_chop",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_quadruple_chop",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Einherjar": {
		"cost": 500,
		"level2_id": "Middle_Einherjar",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Einherjar",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_shockwave": {
		"cost": 500,
		"level2_id": "Middle_shockwave",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_shockwave",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Rot": {
		"cost": 500,
		"level2_id": "Middle_Rot",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Rot",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Blood_grudge_Dagger": {
		"cost": 500,
		"level2_id": "Middle_Blood_grudge_Dagger",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Blood_grudge_Dagger",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_clock_and_dagger": {
		"cost": 500,
		"level2_id": "Middle_clock_and_dagger",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_clock_and_dagger",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_necromastery": {
		"cost": 500,
		"level2_id": "Middle_necromastery",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_necromastery",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_bash_of_the_deep": {
		"cost": 500,
		"level2_id": "Middle_bash_of_the_deep",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_bash_of_the_deep",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Boundless_Strike": {
		"cost": 500,
		"level2_id": "Middle_Boundless_Strike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Boundless_Strike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_assassinate": {
		"cost": 500,
		"level2_id": "Middle_assassinate",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_assassinate",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_corrosive_haze": {
		"cost": 500,
		"level2_id": "Middle_corrosive_haze",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_corrosive_haze",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_invincible_army": {
		"cost": 500,
		"level2_id": "Middle_invincible_army",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_invincible_army",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_chaos_strike": {
		"cost": 500,
		"level2_id": "Middle_chaos_strike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_chaos_strike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Bloodrage": {
		"cost": 500,
		"level2_id": "Middle_Bloodrage",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Bloodrage",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_double_edge": {
		"cost": 500,
		"level2_id": "Middle_double_edge",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_double_edge",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_enchant_totem": {
		"cost": 500,
		"level2_id": "Middle_enchant_totem",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_enchant_totem",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_lucent_beam": {
		"cost": 500,
		"level2_id": "Middle_lucent_beam",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_lucent_beam",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_onslaught": {
		"cost": 500,
		"level2_id": "Middle_onslaught",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_onslaught",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_acorn_shot": {
		"cost": 500,
		"level2_id": "Middle_acorn_shot",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_acorn_shot",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_infernal_blade": {
		"cost": 500,
		"level2_id": "Middle_infernal_blade",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_infernal_blade",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Sharpshooter": {
		"cost": 500,
		"level2_id": "Middle_Sharpshooter",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Sharpshooter",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Moment_of_Courage": {
		"cost": 500,
		"level2_id": "Middle_Moment_of_Courage",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Moment_of_Courage",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Tidebringer": {
		"cost": 500,
		"level2_id": "Middle_Tidebringer",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Tidebringer",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_uproar": {
		"cost": 500,
		"level2_id": "Middle_uproar",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_uproar",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_headshot": {
		"cost": 500,
		"level2_id": "Middle_headshot",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_headshot",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_greater_bash": {
		"cost": 500,
		"level2_id": "Middle_greater_bash",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_greater_bash",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Burning_Spear": {
		"cost": 500,
		"level2_id": "Middle_Burning_Spear",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Burning_Spear",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_moon_glaive": {
		"cost": 500,
		"level2_id": "Middle_moon_glaive",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_moon_glaive",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_berserkers_blood": {
		"cost": 500,
		"level2_id": "Middle_berserkers_blood",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_berserkers_blood",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_seahit": {
		"cost": 500,
		"level2_id": "Middle_seahit",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_seahit",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_eye_of_the_storm": {
		"cost": 500,
		"level2_id": "Middle_eye_of_the_storm",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_eye_of_the_storm",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
};