GameUI.CustomUIConfig().SpellShop_SummonKV = {
	"Primary_Plague_Ward": {
		"cost": 500,
		"level2_id": "Middle_Plague_Ward",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Plague_Ward",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Demonic_Conversion": {
		"cost": 500,
		"level2_id": "Middle_Demonic_Conversion",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Demonic_Conversion",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_wolves": {
		"cost": 500,
		"level2_id": "Middle_summon_wolves",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_wolves",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_Dave_Chisnall": {
		"cost": 750,
		"level2_id": "Middle_summon_Dave_Chisnall",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_summon_Dave_Chisnall",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Soul_Link": {
		"cost": 500,
		"level2_id": "Middle_Soul_Link",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Soul_Link",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Chaotic_Offering": {
		"cost": 750,
		"level2_id": "Middle_Chaotic_Offering",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Chaotic_Offering",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_summon_water_element": {
		"cost": 500,
		"level2_id": "Middle_summon_water_element",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_water_element",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Aethrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Aethrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Aethrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_healing_ward": {
		"cost": 500,
		"level2_id": "Middle_summon_healing_ward",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_healing_ward",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_summon_earth_element": {
		"cost": 500,
		"level2_id": "Middle_summon_earth_element",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_earth_element",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_summons_undead_jack_the_ripper": {
		"cost": 500,
		"level2_id": "Middle_summons_undead_jack_the_ripper",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summons_undead_jack_the_ripper",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Vahdrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Vahdrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Vahdrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Uldorak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Uldorak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Uldorak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Slyrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Slyrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Slyrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Byssrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Byssrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Byssrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Lirrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Lirrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Lirrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Eldwurm_soul_Indrak": {
		"cost": 500,
		"level2_id": "Middle_Eldwurm_soul_Indrak",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Eldwurm_soul_Indrak",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summons_ward_Aghanim_the_Wisest": {
		"cost": 500,
		"level2_id": "Middle_summons_ward_Aghanim_the_Wisest",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summons_ward_Aghanim_the_Wisest",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_summon_Slime": {
		"cost": 500,
		"level2_id": "Middle_summon_Slime",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_Slime",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_Forge_Spirit": {
		"cost": 500,
		"level2_id": "Middle_summon_Forge_Spirit",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_Forge_Spirit",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_demon_dark_rift": {
		"cost": 500,
		"level2_id": "Middle_summon_demon_dark_rift",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_demon_dark_rift",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_humanoid_cave_troll": {
		"cost": 500,
		"level2_id": "Middle_summon_humanoid_cave_troll",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_humanoid_cave_troll",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_summon_wind_element": {
		"cost": 500,
		"level2_id": "Middle_summon_wind_element",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_wind_element",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_summon_immortal_sarcophagus": {
		"cost": 500,
		"level2_id": "Middle_summon_immortal_sarcophagus",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_summon_immortal_sarcophagus",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
};