GameUI.CustomUIConfig().SpellShop_MagicalKV = {
	"Primary_Death_Pulse": {
		"cost": 500,
		"level2_id": "Middle_Death_Pulse",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Death_Pulse",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Ghost_Shroud": {
		"cost": 500,
		"level2_id": "Middle_Ghost_Shroud",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ghost_Shroud",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Heart_Stopper_Aura": {
		"cost": 500,
		"level2_id": "Middle_Heart_Stopper_Aura",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Heart_Stopper_Aura",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Reapers_Scythe": {
		"cost": 500,
		"level2_id": "Middle_Reapers_Scythe",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Reapers_Scythe",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Venomous_Gale": {
		"cost": 500,
		"level2_id": "Middle_Venomous_Gale",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Venomous_Gale",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Poison_Sting": {
		"cost": 500,
		"level2_id": "Middle_Poison_Sting",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Poison_Sting",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Poison_Nova": {
		"cost": 500,
		"level2_id": "Middle_Poison_Nova",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Poison_Nova",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Ice_Vortex": {
		"cost": 500,
		"level2_id": "Middle_Ice_Vortex",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ice_Vortex",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Chilling_Touch": {
		"cost": 500,
		"level2_id": "Middle_Chilling_Touch",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Chilling_Touch",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Dual_Breath": {
		"cost": 500,
		"level2_id": "Middle_Dual_Breath",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Dual_Breath",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Ice_Path": {
		"cost": 500,
		"level2_id": "Middle_Ice_Path",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ice_Path",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Liquid_Fire": {
		"cost": 500,
		"level2_id": "Middle_Liquid_Fire",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Liquid_Fire",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Liquid_Frost": {
		"cost": 500,
		"level2_id": "Middle_Liquid_Frost",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Liquid_Frost",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Macropyre": {
		"cost": 500,
		"level2_id": "Middle_Macropyre",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Macropyre",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Malefice": {
		"cost": 500,
		"level2_id": "Middle_Malefice",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Malefice",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Midnight_Pulse": {
		"cost": 500,
		"level2_id": "Middle_Midnight_Pulse",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Midnight_Pulse",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Black_Hole": {
		"cost": 750,
		"level2_id": "Middle_Black_Hole",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Black_Hole",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Nether_Blast": {
		"cost": 500,
		"level2_id": "Middle_Nether_Blast",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Nether_Blast",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Nether_Ward": {
		"cost": 750,
		"level2_id": "Middle_Nether_Ward",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Nether_Ward",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Life_Drain": {
		"cost": 500,
		"level2_id": "Middle_Life_Drain",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Life_Drain",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Impetus": {
		"cost": 500,
		"level2_id": "Middle_Impetus",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Impetus",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Arc_Lightning": {
		"cost": 500,
		"level2_id": "Middle_Arc_Lightning",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Arc_Lightning",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Lightning_Bolt": {
		"cost": 500,
		"level2_id": "Middle_Lightning_Bolt",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Lightning_Bolt",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Static_Field": {
		"cost": 500,
		"level2_id": "Middle_Static_Field",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Static_Field",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Thundergods_Wrath": {
		"cost": 750,
		"level2_id": "Middle_Thundergods_Wrath",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Thundergods_Wrath",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_spirits": {
		"cost": 500,
		"level2_id": "Middle_spirits",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_spirits",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_fortunes_end": {
		"cost": 500,
		"level2_id": "Middle_fortunes_end",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_fortunes_end",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_chaos_form": {
		"cost": 500,
		"level2_id": "Middle_chaos_form",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_chaos_form",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_magic_blessing": {
		"cost": 500,
		"level2_id": "Middle_magic_blessing",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_magic_blessing",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_earth_spike": {
		"cost": 500,
		"level2_id": "Middle_earth_spike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_earth_spike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_aether_remnant": {
		"cost": 500,
		"level2_id": "Middle_aether_remnant",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_aether_remnant",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_dissimilate": {
		"cost": 500,
		"level2_id": "Middle_dissimilate",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_dissimilate",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_astral_step": {
		"cost": 500,
		"level2_id": "Middle_astral_step",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_astral_step",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_split_earth": {
		"cost": 500,
		"level2_id": "Middle_split_earth",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_split_earth",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_lightning_storm": {
		"cost": 500,
		"level2_id": "Middle_lightning_storm",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_lightning_storm",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_pulse_nova": {
		"cost": 750,
		"level2_id": "Middle_pulse_nova",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_pulse_nova",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_dragon_slave": {
		"cost": 500,
		"level2_id": "Middle_dragon_slave",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_dragon_slave",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_laguna_blade": {
		"cost": 500,
		"level2_id": "Middle_laguna_blade",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_laguna_blade",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Dragons_Lighting": {
		"cost": 500,
		"level2_id": "Middle_Dragons_Lighting",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Dragons_Lighting",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_stroke_of_fate": {
		"cost": 500,
		"level2_id": "Middle_stroke_of_fate",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_stroke_of_fate",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_laser": {
		"cost": 500,
		"level2_id": "Middle_laser",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_laser",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Chaos_Meteor": {
		"cost": 500,
		"level2_id": "Middle_Chaos_Meteor",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Chaos_Meteor",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_gravity": {
		"cost": 500,
		"level2_id": "Middle_gravity",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_gravity",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_astral_imprisonment": {
		"cost": 500,
		"level2_id": "Middle_astral_imprisonment",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_astral_imprisonment",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_hyakkiyakou": {
		"cost": 500,
		"level2_id": "Middle_hyakkiyakou",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_hyakkiyakou",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Thunderstrike": {
		"cost": 500,
		"level2_id": "Middle_Thunderstrike",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Thunderstrike",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Acid_bomb": {
		"cost": 500,
		"level2_id": "Middle_Acid_bomb",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Acid_bomb",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_finger_of_death": {
		"cost": 500,
		"level2_id": "Middle_finger_of_death",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_finger_of_death",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_brain_sap": {
		"cost": 500,
		"level2_id": "Middle_brain_sap",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_brain_sap",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_light_strike_array": {
		"cost": 500,
		"level2_id": "Middle_light_strike_array",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_light_strike_array",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_fiery_soul": {
		"cost": 500,
		"level2_id": "Middle_fiery_soul",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_fiery_soul",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_arcane_bolt": {
		"cost": 500,
		"level2_id": "Middle_arcane_bolt",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_arcane_bolt",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Arcane_Replacement": {
		"cost": 500,
		"level2_id": "Middle_Arcane_Replacement",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Arcane_Replacement",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_ancient_seal": {
		"cost": 500,
		"level2_id": "Middle_ancient_seal",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_ancient_seal",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_mystic_flare": {
		"cost": 500,
		"level2_id": "Middle_mystic_flare",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_mystic_flare",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Doom": {
		"cost": 500,
		"level2_id": "Middle_Doom",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Doom",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_heat_seeking_missile": {
		"cost": 500,
		"level2_id": "Middle_heat_seeking_missile",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_heat_seeking_missile",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Overload": {
		"cost": 500,
		"level2_id": "Middle_Overload",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Overload",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_pierce_the_veil": {
		"cost": 750,
		"level2_id": "Middle_pierce_the_veil",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_pierce_the_veil",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Ghost_Saya": {
		"cost": 500,
		"level2_id": "Middle_Ghost_Saya",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ghost_Saya",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_arcane_supremacy": {
		"cost": 500,
		"level2_id": "Middle_arcane_supremacy",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_arcane_supremacy",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_elder_dragon_form_ice": {
		"cost": 500,
		"level2_id": "Middle_elder_dragon_form_ice",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_elder_dragon_form_ice",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 30,
	},
	"Primary_Poison_Touch": {
		"cost": 500,
		"level2_id": "Middle_Poison_Touch",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Poison_Touch",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_ravage": {
		"cost": 500,
		"level2_id": "Middle_ravage",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_ravage",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
};