GameUI.CustomUIConfig().SpellShop_AssistKV = {
	"Primary_Warcry": {
		"cost": 500,
		"level2_id": "Middle_Warcry",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Warcry",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Viscous_Nasal_Goo": {
		"cost": 500,
		"level2_id": "Middle_Viscous_Nasal_Goo",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Viscous_Nasal_Goo",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Blood_Lust": {
		"cost": 500,
		"level2_id": "Middle_Blood_Lust",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Blood_Lust",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Shallow_Grave": {
		"cost": 500,
		"level2_id": "Middle_Shallow_Grave",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Shallow_Grave",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Shadow_Wave": {
		"cost": 500,
		"level2_id": "Middle_Shadow_Wave",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Shadow_Wave",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Bad_Juju": {
		"cost": 750,
		"level2_id": "Middle_Bad_Juju",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_Bad_Juju",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Decrepify": {
		"cost": 500,
		"level2_id": "Middle_Decrepify",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Decrepify",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Nature_Attendants": {
		"cost": 500,
		"level2_id": "Middle_Nature_Attendants",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Nature_Attendants",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_mist_coil": {
		"cost": 500,
		"level2_id": "Middle_mist_coil",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_mist_coil",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_aphotic_shield": {
		"cost": 500,
		"level2_id": "Middle_aphotic_shield",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_aphotic_shield",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_tether": {
		"associated_spells": "Primary_tether_break",
		"cost": 500,
		"level2_id": "Middle_tether",
		"level2_associated_spells": "Middle_tether_break",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_tether",
		"level3_associated_spells": "Advanced_tether_break",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_overcharge": {
		"cost": 500,
		"level2_id": "Middle_overcharge",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_overcharge",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 30,
	},
	"Primary_purifying_flames": {
		"cost": 500,
		"level2_id": "Middle_purifying_flame",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_purifying_flame",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_fates_edict": {
		"cost": 500,
		"level2_id": "Middle_fates_edict",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_fates_edict",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_false_promise": {
		"cost": 750,
		"level2_id": "Middle_false_promise",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_false_promise",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_purification": {
		"cost": 500,
		"level2_id": "Middle_purification",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_purification",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_repel": {
		"cost": 500,
		"level2_id": "Middle_repel",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_repel",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_infest": {
		"cost": 750,
		"level2_id": "Middle_infest",
		"to_level2_cost": 1500,
		"level3_id": "Advanced_infest",
		"to_level3_cost": 2200,
		"upgrade_cost": 750,
		"weight": 100,
	},
	"Primary_Inner_Beast": {
		"cost": 500,
		"level2_id": "Middle_Inner_Beast",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Inner_Beast",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Arcane_Aura": {
		"cost": 500,
		"level2_id": "Middle_Arcane_Aura",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Arcane_Aura",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_frost_armor": {
		"cost": 500,
		"level2_id": "Middle_frost_armor",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_frost_armor",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_Vengeance_Aura": {
		"cost": 500,
		"level2_id": "Middle_Vengeance_Aura",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Vengeance_Aura",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_aftershock": {
		"cost": 500,
		"level2_id": "Middle_aftershock",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_aftershock",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Chakra": {
		"cost": 500,
		"level2_id": "Middle_Chakra",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Chakra",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Voodoo_Restoration": {
		"cost": 500,
		"level2_id": "Middle_Voodoo_Restoration",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Voodoo_Restoration",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Vampiric_Spirit": {
		"cost": 500,
		"level2_id": "Middle_Vampiric_Spirit",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Vampiric_Spirit",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_empower": {
		"cost": 500,
		"level2_id": "Middle_empower",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_empower",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_fear_arua": {
		"cost": 500,
		"level2_id": "Middle_fear_arua",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_fear_arua",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_water_prison": {
		"cost": 500,
		"level2_id": "Middle_water_prison",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_water_prison",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_cold_embrace": {
		"cost": 500,
		"level2_id": "Middle_cold_embrace",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_cold_embrace",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_howl": {
		"cost": 500,
		"level2_id": "Middle_howl",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_howl",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
	"Primary_lunar_blessing": {
		"cost": 500,
		"level2_id": "Middle_lunar_blessing",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_lunar_blessing",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_reverse_polarity": {
		"cost": 500,
		"level2_id": "Middle_reverse_polarity",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_reverse_polarity",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_presence_of_the_dark_lord": {
		"cost": 500,
		"level2_id": "Middle_presence_of_the_dark_lord",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_presence_of_the_dark_lord",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Ghost_Purimn": {
		"cost": 500,
		"level2_id": "Middle_Ghost_Purimn",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ghost_Purimn",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Ghost_Rocha": {
		"cost": 500,
		"level2_id": "Middle_Ghost_Rocha",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Ghost_Rocha",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_vaccum": {
		"cost": 500,
		"level2_id": "Middle_vaccum",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_vaccum",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"weight": 100,
	},
	"Primary_Anti_time": {
		"cost": 500,
		"level2_id": "Middle_Anti_time",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_Anti_time",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 60,
	},
	"Primary_curse": {
		"cost": 500,
		"level2_id": "Middle_curse",
		"to_level2_cost": 1000,
		"level3_id": "Advanced_curse",
		"to_level3_cost": 1500,
		"upgrade_cost": 500,
		"Recommended": 1,
		"weight": 100,
	},
};