"KeyValue"
{
	"item_hd_the_first_core"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"15000"
	}
	"item_hd_the_second_core"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"15000"
	}
	"item_hd_the_third_core"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"15000"
	}
	"item_chaotic_sword_of_seven"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_critdrow"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_ballista"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_butterfly"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_dagon"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_dezun_bloodrite"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_devastator"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_unrelenting_eye"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_roshan_heart"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_glimmerdark_shield"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_necronomicon_1"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_necronomicon_2"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_roshan_flag_defense"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_roshan_flag_attack"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_roshan_flag_cooldown"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_proficstaff"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_crown"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_crown_alter"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_element_stone"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_blink_str"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_blink_agi"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_blink_int"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"8000"
	}
	"item_chaotic_circlet"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_broadsword"
	{
		"type"									"physical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_blitz_knuckles"
	{
		"type"									"physical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_possessed_mask"
	{
		"type"									"physical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_bogduggs_baldric"
	{
		"type"									"armor"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_blight_stone"
	{
		"type"									"physical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_Claw_of_attack"
	{
		"type"									"physical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_sobi_mask"
	{
		"type"									"magical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_mysterious_hat"
	{
		"type"									"magical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_keen_optic"
	{
		"type"									"magical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_amulet"
	{
		"type"									"magical_weapon"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_shaman_skull"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_shaman_necklace"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_chipped_vest"
	{
		"type"									"armor"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_energy_ring"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_arcane_ring"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_nian_flag_trap"
	{
		"type"									"subsidiarity"
		"level"									"1"
		"cost"									"500"
	}
	"item_hd_dust"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_chaotic_blade_of_alacrity"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_phase_boots"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_Yasha"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_vambrace"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_quicksilver_amulet"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_medallion_of_courage"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_jack_the_rippers_claw"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_anger_coat"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_javelin"
	{
		"type"									"physical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_staff_of_wizardry"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_tranquil_boots"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_nether_shawl"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_Kaya"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_secret_of_summon"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_soul_of_orc"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_arcane_hat"
	{
		"type"									"magical_weapon"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_power_treads"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_dragon_scale"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_sange"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_hood_of_defiance"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_vanguard"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_demons_heart_02"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_vitality_booster"
	{
		"type"									"armor"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_arcane_boots"
	{
		"type"									"subsidiarity"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_pheromone"
	{
		"type"									"subsidiarity"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_Ice_coat"
	{
		"type"									"subsidiarity"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_shadow_amulet"
	{
		"type"									"special"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_precious_egg"
	{
		"type"									"special"
		"level"									"2"
		"cost"									"1000"
	}
	"item_chaotic_book_of_torture"
	{
		"type"									"special"
		"level"									"2"
		"cost"									"1000"
	}
	"item_hd_invis_sword"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_paladin_sword"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_orb_of_destruction"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_mind_breaker"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_elven_tunic"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_paw_of_lucius"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_lesser_crit"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_balnock_spear"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_demon_edge"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_eagle"
	{
		"type"									"physical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_ninja_gear"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_the_leveller"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_phase_boots_2"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_penta_edged_sword"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_echo_sabre"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_polar_shadow_double_blades"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_silver_strike_blade"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_dark_night_guard_handguard"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_diffusal_blade"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_advanced_Claw_of_attack"
	{
		"type"									"physical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_bloodthorn"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_silver_edge"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_skadi"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_satanic"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_desolator_2"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_mjollnir"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_butterfly"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_monkey_king_bar"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_slark_double_blades"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_start_sword"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_eagle_ring"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rivers_of_blood"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_agi_ring"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_assassin_veil"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_jasper_daggers"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_god_slaying_emperor_blade"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_siren_clothing"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_head_of_medusa"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_sven_mask"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_shisui"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_horn_of_the_alpha"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_tesla_high_energy_gun"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ritual_spear"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_circlet_of_dark_and_light"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_cantern_of_servitude"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ring_of_flowing_wind"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_maelstrom"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_orchid"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_star_calling_cloak"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_deathly_scepter"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_enchanted_quiver"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_psychic_headband"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_cyclone_2"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_soul_of_balnock"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_mystic_staff"
	{
		"type"									"magical_weapon"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_timeless_relic"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_spell_prism"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_minotaur_horn"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Yasha_and_Kaya"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_tranquil_boots_2"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Kaya_and_Sange"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_stormcrafter"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_moonrift_longbow"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_wolf_king_mask"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Stonework_Pendant"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_witchbane"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_eye_of_the_vizier"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_bloodthorn_magic"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_octarine_core_level3"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_the_secret_of_light"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_seer_stone"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_antarctic_star_spear"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_verodicias_rune_staff"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_bloodstone"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_wind_waker"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_philosopher_stone"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_moirai_hat"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_book_of_death"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ancient_gemstone"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_potion_of_planar"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_thunder"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_int_ring"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_cloak_of_endless_carnage"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_obliterating_orb"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_hero_cape"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rose_scepter"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_helm_of_the_overlord"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_shivas_staff"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_argo_paw"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_poison_coat"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_glimmer_cape"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_blade_mail"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_valhalla_helmet"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_holy_cross_amulet"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_titan_sliver"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_cloak_of_flames"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_craggy_coat"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_balnock_shield"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_reaver"
	{
		"type"									"armor"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_trickster_cloak"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Sange_and_Yasha"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_heavens_halberd"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hero_carapace_of_qaldin"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_eternal_shroud"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_power_treads_2"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_breath_of_life"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Guardian_Shel"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_panic_button"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_combo_breaker"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_crimson_guard"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_titan_stone"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_shivas_guard"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ex_machina"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_giants_ring"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_heart"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_assault"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_radiance"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_remnant_spirit_of_the_ancient_tree"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_witless_shako"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_Siltbreaker_Glimmerdark_Shield"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_Harlequin_green_hat"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_str_ring"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_viigil_signet"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_remnant_sun_prison_garb"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_shield_of_aquila"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_claszureme_hourglass"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_seraphim_shield"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ristul_emblem"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_demagicking_maul"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_kraken_shell_armor"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_siltbreaker_rhyzik_eye"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_brain_worm"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_helm_of_disjunction"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_horn_of_winter"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_mythrienss_ring"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_font_of_time"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_shield_of_the_hidden_lord_1"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_starry_sky_dome"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_defiant_shell"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_modular_armor"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_blood_bug_barrier"
	{
		"type"									"armor"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_vladmir"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_holy_locket"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_anti_energy_ring_2"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_energy_ring_2"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_arcane_ring_2"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_anti_arcane_ring_2"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_ceremonial_robe"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_force_staff"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_ring_of_aquila"
	{
		"type"									"subsidiarity"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_spy_gadget"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_arcane_boots_2"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_holy_cross_cloak"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_holy_cross_battlefield"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_holy_cross_hand_guard"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Ambient_Sorcery"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_sheepstick"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_grandmasters_glaive"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Watcher_Gaze"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Preserved_Skull"
	{
		"type"									"subsidiarity"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_lamb_divine_staff"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_saurian_fasciculus"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ice_blossom"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_yulsarias_glacier"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_alluvion_prophecy"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_sagas_of_the_cymurrin_sage"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_yulsarias_mantle"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_paragons_rebuke"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_fetters_of_omniscience"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ice_ring"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_fate_ring"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_witch_crown"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rumusque_vestments"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_high_priest_robe"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_tears_of_aquastar"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_wingfall_hammer"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_tome_of_living_memories1"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_helm_of_omni"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_scarecrow_hat"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_broken_promise"
	{
		"type"									"subsidiarity"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_soul_booster"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_quickening_charm"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_spider_legs"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_risk_dice"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_shield_of_lackeys"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_staff_of_lackeys"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_bottle_water"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_ultimate_orb"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_secret_of_experience"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_soul_2"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_dust2"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_revtel_signet_ring"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_blink"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_flicker"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_travel_boots_lv2"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_secret_of_time"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_Siltbreaker_Unhallowed"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_black_king_bar"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"5000"
	}
	"item_hd_sphere"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_moon_shard"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_arcana_blink"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_aghanims_shard"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_bottle_invisibility"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_force_boots"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_mirror_shield"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_apex"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_fallen_sky"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_trident"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_ancient_living_stone"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_Blessing_of_the_Chanter"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_hermes_boots"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_galaxy_compass"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rubick_cube"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rubick_cube2"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_phoenix_ring"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_book_of_death_2"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_advanced_keen_optic"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_bogduggs_lucky_femur"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_selecter_terminal"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_bottledthundertorm"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_chrono_casket"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_flash_change_brooch"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_thousand_leagues_astrologer"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_modular_boots"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_guardian_ring"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_revenants_brooch_player"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_rule_breaker"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_song_of_ice_and_fire"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_poison_lokustra"
	{
		"type"									"magical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_iron_part"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_bfury_plus"
	{
		"type"									"physical_weapon"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_poison_ball"
	{
		"type"									"armor"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_poison_fog"
	{
		"type"									"magical_weapon"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_madstone_bundle"
	{
		"type"									"special"
		"level"									"1"
		"cost"									"500"
	}
	"item_hd_occult_bracelet"
	{
		"type"									"special"
		"level"									"2"
		"cost"									"1000"
	}
	"item_hd_point_booster"
	{
		"type"									"special"
		"level"									"3"
		"cost"									"2000"
	}
	"item_hd_lotus_orb"
	{
		"type"									"special"
		"level"									"4"
		"cost"									"3000"
	}
	"item_hd_enhancement_wise"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"3000"
	}
	"item_hd_third_eye"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_travel_boots_tinker"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_dandelion_amulet"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_refresher"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_outworld_staff"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
	"item_hd_disperser"
	{
		"type"									"special"
		"level"									"5"
		"cost"									"5000"
	}
}
