"KeyValue"
{
	"item_secret_of_experience"
	{
		"type"									"consumables"
		"cost"									"4000"
	}
	"item_hd_Treasure1_shop"
	{
		"type"									"consumables"
		"cost"									"1000"
	}
	"item_hd_Treasure2_shop"
	{
		"type"									"consumables"
		"cost"									"2000"
	}
	"item_hd_Treasure3_shop"
	{
		"type"									"consumables"
		"cost"									"3000"
	}
	"item_hd_Treasure4_shop"
	{
		"type"									"consumables"
		"cost"									"8000"
	}
	"item_hd_Treasure5_shop"
	{
		"type"									"consumables"
		"cost"									"50000"
	}
	"item_hd_courier_radiant"
	{
		"type"									"consumables"
		"cost"									"600"
	}
	"item_hd_skeletology"
	{
		"type"									"consumables"
		"cost"									"1200"
	}
	"item_hd_advanced_mathematics"
	{
		"type"									"consumables"
		"cost"									"1500"
	}
	"item_hd_introduction_of_arcane"
	{
		"type"									"consumables"
		"cost"									"1500"
	}
	"item_hd_neutral"
	{
		"type"									"consumables"
		"cost"									"2000"
	}
	"item_new_bottle_1"
	{
		"type"									"consumables"
		"cost"									"300"
	}
	"item_new_bottle_2"
	{
		"type"									"consumables"
		"cost"									"300"
	}
	"item_new_bottle_3"
	{
		"type"									"consumables"
		"cost"									"300"
	}
	"item_new_bottle_4"
	{
		"type"									"consumables"
		"cost"									"300"
	}
	"item_new_bottle_5"
	{
		"type"									"consumables"
		"cost"									"300"
	}
	"item_new_bottle_sup"
	{
		"type"									"consumables"
		"cost"									"1000"
	}
	"item_hd_voodoo_mask"
	{
		"type"									"Equipment"
		"cost"									"700"
	}
	"item_hd_Morbid_Mask"
	{
		"type"									"Equipment"
		"cost"									"700"
	}
	"item_hd_mango_tree"
	{
		"type"									"Equipment"
		"cost"									"1000"
	}
	"item_hd_sparkle"
	{
		"type"									"Equipment"
		"cost"									"2300"
	}
	"item_hd_SilenceDarkness"
	{
		"type"									"Equipment"
		"cost"									"2300"
	}
	"item_hd_poison_coat"
	{
		"type"									"Equipment"
		"cost"									"2000"
	}
	"item_hd_anti_arcane_ring_2"
	{
		"type"									"Equipment"
		"cost"									"3000"
	}
	"item_hd_anti_energy_ring_2"
	{
		"type"									"Equipment"
		"cost"									"3000"
	}
	"item_hd_black_king_bar"
	{
		"type"									"Equipment"
		"cost"									"5500"
	}
	"item_hd_combo_breaker"
	{
		"type"									"Equipment"
		"cost"									"5500"
	}
	"item_bfury_level1"
	{
		"type"									"Equipment"
		"cost"									"5500"
	}
}
