"KeyValue"
{
	"Primary_Bulwark"
	{
		"cost"									"500"
		"level2_id"								"Middle_Bulwark"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Bulwark"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"Recommended"							"1"
		"weight"								"100"
	}
	"Primary_Dispersion"
	{
		"cost"									"500"
		"level2_id"								"Middle_Dispersion"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Dispersion"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Berserkers_Call"
	{
		"cost"									"500"
		"level2_id"								"Middle_Berserkers_Call"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Berserkers_Call"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"50"
	}
	"Primary_Counter_Helix"
	{
		"cost"									"500"
		"level2_id"								"Middle_Counter_Helix"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Counter_Helix"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Bristle_Back"
	{
		"cost"									"500"
		"level2_id"								"Middle_Bristle_Back"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Bristle_Back"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Untouchable"
	{
		"cost"									"500"
		"level2_id"								"Middle_Untouchable"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Untouchable"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_borrowed_time"
	{
		"cost"									"750"
		"level2_id"								"Middle_borrowed_time"
		"to_level2_cost"						"1500"
		"level3_id"								"Advanced_borrowed_time"
		"to_level3_cost"						"2200"
		"upgrade_cost"							"750"
		"weight"								"100"
	}
	"Primary_dragon_blood"
	{
		"cost"									"500"
		"level2_id"								"Middle_dragon_blood"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_dragon_blood"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_kraken_shell"
	{
		"cost"									"500"
		"level2_id"								"Middle_kraken_shell"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_kraken_shell"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_reactive_armor"
	{
		"cost"									"500"
		"level2_id"								"Middle_reactive_armor"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_reactive_armor"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"15"
	}
	"Primary_true_form"
	{
		"cost"									"500"
		"level2_id"								"Middle_true_form"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_true_form"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_counterspell"
	{
		"cost"									"500"
		"level2_id"								"Middle_counterspell"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_counterspell"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_reincarnation"
	{
		"cost"									"750"
		"level2_id"								"Middle_reincarnation"
		"to_level2_cost"						"1500"
		"level3_id"								"Advanced_reincarnation"
		"to_level3_cost"						"2200"
		"upgrade_cost"							"750"
		"weight"								"100"
	}
	"Primary_rage"
	{
		"cost"									"500"
		"level2_id"								"Middle_rage"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_rage"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_enrage"
	{
		"cost"									"500"
		"level2_id"								"Middle_enrage"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_enrage"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_mana_shield"
	{
		"cost"									"500"
		"level2_id"								"Middle_mana_shield"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_mana_shield"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_return"
	{
		"cost"									"500"
		"level2_id"								"Middle_return"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_return"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Body_of_Effulgent_Beryl"
	{
		"cost"									"500"
		"level2_id"								"Middle_Body_of_Effulgent_Beryl"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Body_of_Effulgent_Beryl"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Corrosive_Skin"
	{
		"cost"									"750"
		"level2_id"								"Middle_Corrosive_Skin"
		"to_level2_cost"						"1500"
		"level3_id"								"Advanced_Corrosive_Skin"
		"to_level3_cost"						"2200"
		"upgrade_cost"							"750"
		"weight"								"100"
	}
	"Primary_Electrostatic_Armor"
	{
		"cost"									"500"
		"level2_id"								"Middle_Electrostatic_Armor"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Electrostatic_Armor"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"50"
	}
	"Primary_whirling_death"
	{
		"cost"									"500"
		"level2_id"								"Middle_whirling_death"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_whirling_death"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Holy_Light_Shield"
	{
		"cost"									"500"
		"level2_id"								"Middle_Holy_Light_Shield"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Holy_Light_Shield"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"Recommended"							"1"
		"weight"								"100"
	}
	"Primary_shield_crash"
	{
		"cost"									"500"
		"level2_id"								"Middle_shield_crash"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_shield_crash"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"Recommended"							"1"
		"weight"								"100"
	}
	"Primary_bulldoze"
	{
		"cost"									"500"
		"level2_id"								"Middle_bulldoze"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_bulldoze"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Refraction"
	{
		"cost"									"500"
		"level2_id"								"Middle_Refraction"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Refraction"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
}
