"KeyValue"
{
	"for_swap_spells"
	{
		"cost"									"0"
		"level2_id"								"for_swap_spells"
		"to_level2_cost"						"0"
		"level3_id"								"for_swap_spells"
		"to_level3_cost"						"0"
		"upgrade_cost"							"0"
		"weight"								"0"
	}
	"Primary_Void_time_walk"
	{
		"cost"									"500"
		"level2_id"								"Middle_Void_time_walk"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Void_time_walk"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Time_Drain"
	{
		"cost"									"500"
		"level2_id"								"Middle_Time_Drain"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Time_Drain"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Chronosphere"
	{
		"cost"									"750"
		"level2_id"								"Middle_Chronosphere"
		"to_level2_cost"						"1500"
		"level3_id"								"Advanced_Chronosphere"
		"to_level3_cost"						"2200"
		"upgrade_cost"							"750"
		"weight"								"100"
	}
	"Primary_Blood_Sacrifice"
	{
		"cost"									"500"
		"level2_id"								"Middle_Blood_Sacrifice"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Blood_Sacrifice"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Windrun"
	{
		"cost"									"500"
		"level2_id"								"Middle_Windrun"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Windrun"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Greevils_Greed"
	{
		"cost"									"500"
		"level2_id"								"Middle_Greevils_Greed"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Greevils_Greed"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"0"
	}
	"Primary_cook"
	{
		"cost"									"500"
		"level2_id"								"Middle_cook"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_cook"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_timber_chain"
	{
		"cost"									"500"
		"level2_id"								"Middle_timber_chain"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_timber_chain"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_morph"
	{
		"cost"									"500"
		"level2_id"								"Middle_morph"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_morph"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_trace_on"
	{
		"cost"									"500"
		"level2_id"								"Middle_trace_on"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_trace_on"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_Nightmare"
	{
		"cost"									"500"
		"level2_id"								"Middle_Nightmare"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_Nightmare"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"100"
	}
	"Primary_talentgain"
	{
		"cost"									"500"
		"level2_id"								"Middle_talentgain"
		"to_level2_cost"						"1000"
		"level3_id"								"Advanced_talentgain"
		"to_level3_cost"						"1500"
		"upgrade_cost"							"500"
		"weight"								"30"
	}
}
