"KeyValue"
{
	"general_talent_magic_insider"
	{
		"AbilityTextureName"					"general_talent/general_talent_magic_insider"
		"ScriptFile"							"heroTalent_general/general_talent_magical"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"MaxLevel"								"1"
		"AbilityCastPoint"						"0.5"
		"AbilityCastAnimation"					"ACT_DOTA_ATTACK"
		"AbilityValues"
		{
			"bonus_damage"						"5"
			"bonus_damage_low"					"50"
		}
		"BaseClass"								"ability_lua"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"LevelsBetweenUpgrades"					"0"
	}
	"general_talent_budget_strictly"
	{
		"BaseClass"								"ability_lua"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"LevelsBetweenUpgrades"					"0"
	}
}
