"KeyValue"
{
	"modifier_lifeseeker_lifesteal"
	{
		"AbilityValues"
		{
			"value1"							"500"
		}
		"texture"								"life_stealer_feast"
	}
	"modifier_chaotic_era_assassin"
	{
		"AbilityValues"
		{
			"value1"							"200"
		}
		"texture"								"invoker_ghost_walk"
	}
	"modifier_chaotic_era_thirsty_furblog"
	{
		"AbilityValues"
		{
			"value1"							"10"
		}
		"texture"								"bloodseeker/bloodseeker_ti_immortal/bloodseeker_thirst_alt"
	}
	"modifier_chaotic_era_sharp_tooth_raider"
	{
		"AbilityValues"
		{
			"value1"							"10"
		}
		"texture"								"life_stealer/promo_bloody_ripper_abilityicons/life_stealer_consume"
	}
	"modifier_chaotic_era_undying"
	{
		"AbilityValues"
		{
			"value1"							"2"
			"value2"							"10"
		}
		"texture"								"life_stealer_consume"
	}
	"modifier_chaotic_era_lava_attack"
	{
		"AbilityValues"
		{
			"value1"							"400"
			"value2"							"40"
		}
		"texture"								"earthshaker/sltv__earthshaker_ability_icons/earthshaker_fissure"
	}
	"modifier_chaotic_era_chaotic_executive"
	{
		"AbilityValues"
		{
			"value1"							"5"
			"value2"							"30"
		}
		"texture"								"enigma_malefice"
	}
	"modifier_chaotic_era_super_boxing"
	{
		"AbilityValues"
		{
			"value1"							"8"
			"value2"							"120"
		}
		"texture"								"ember_spirit_sleight_of_fist"
	}
	"modifier_chaotic_era_hypnotic_pollen"
	{
		"AbilityValues"
		{
			"value1"							"4"
			"value2"							"15"
			"value3"							"100"
			"distance"							"300"
		}
		"texture"								"furion_wrath_of_nature_ti9"
	}
	"modifier_chaotic_era_self_regen"
	{
		"AbilityValues"
		{
			"value1"							"1"
		}
		"texture"								"enchantress_natures_attendants"
	}
	"modifier_chaotic_era_poison_boom"
	{
		"AbilityValues"
		{
			"value1"							"360"
			"value2"							"30"
			"value3"							"1"
		}
		"texture"								"greevil_rot"
	}
	"modifier_chaotic_era_sea_attack"
	{
		"AbilityValues"
		{
			"value1"							"12"
			"value2"							"30"
			"value3"							"0.3"
		}
		"texture"								"phantom_assassin_armor_corruption_debuff"
	}
	"modifier_chaotic_era_acid_attack"
	{
		"AbilityValues"
		{
			"value1"							"2"
			"value2"							"3"
			"value3"							"5"
		}
		"texture"								"morphling_adaptive_strike_str"
	}
	"modifier_chaotic_era_ice_attack"
	{
		"AbilityValues"
		{
			"value1"							"10"
			"value2"							"5"
		}
		"texture"								"ancient_apparition_ice_blast_release"
	}
}
