
--储存道具的table
--在进行升级道具时会基于其价格判断等级
_G.WAVE_Bonus_Items = {
    --物理攻击性装备
    physical_weapon = {
        level1 = {
            "item_hd_Claw_of_attack",
            "item_hd_broom_handle",
            -- "item_hd_Morbid_Mask",
            "item_hd_quelling_blade",
            "item_hd_blight_stone",
            "item_hd_evil_resentment",
            "item_hd_snipers_firecracker",
            "item_hd_iron_talon",
            "item_hd_falcon_blade",
            "item_hd_gloves",

        },
        level2 = {
            "item_hd_blade_of_alacrity",
            "item_hd_phase_boots",
            "item_hd_Yasha",
            "item_hd_imp_claw",
            "item_hd_grove_bow",
            "item_hd_vambrace_agi",
            "item_hd_quicksilver_amulet",
            "item_hd_medallion_of_courage",
            "item_hd_jack_the_rippers_claw",
            "item_hd_anger_coat",
            "item_hd_javelin",
             

        },
        level3 = {
            "item_hd_invis_sword",
            "item_hd_paladin_sword",
            "item_hd_orb_of_destruction",
            "item_hd_mind_breaker",
            "item_hd_elven_tunic",
            "item_hd_paw_of_lucius",
            "item_hd_lesser_crit",
            "item_hd_balnock_spear",
            "item_hd_demon_edge",
            "item_hd_eagle",
            
            

        },
        level4 = {
            "item_hd_ninja_gear",
            "item_hd_the_leveller",
            -- "item_bfury_level1",
            "item_hd_phase_boots_2",
            "item_hd_penta_edged_sword",
            "item_hd_echo_sabre",
            "item_hd_polar_shadow_double_blades",
            "item_hd_silver_strike_blade",
            "item_hd_dark_night_guard_handguard",
            "item_hd_diffusal_blade",
            "item_hd_advanced_Claw_of_attack",

        },
        level5 = {
            "item_hd_bloodthorn",
            "item_hd_silver_edge",
            "item_hd_skadi",
            "item_hd_satanic",
            "item_hd_desolator_2",
            "item_hd_ballista",
            "item_hd_mjollnir",
            "item_hd_butterfly",
            "item_hd_monkey_king_bar",
            "item_hd_slark_double_blades",
            "item_hd_start_sword",
            "item_hd_eagle_ring",
            "item_hd_rivers_of_blood",
            "item_hd_agi_ring",
            "item_hd_assassin_veil",
            "item_hd_jasper_daggers",
            "item_hd_god_slaying_emperor_blade",
            "item_hd_siren_clothing",
            "item_hd_head_of_medusa",
            "item_hd_sven_mask",
            "item_hd_shisui",
            "item_hd_horn_of_the_alpha",
            "item_hd_tesla_high_energy_gun",
            "item_hd_ritual_spear",
            "item_hd_circlet_of_dark_and_light",
            "item_hd_cantern_of_servitude",
            "item_hd_song_of_ice_and_fire",
            "item_hd_bfury_plus",
            "item_hd_disperser"
        },
        --6级物品一般不由过关奖励产生
        level6 = {
            "item_hd_infernal_menace",
            "item_hd_the_trident_of_the_sunken_treasure_house",
            "item_hd_wind_blaster",
        },

        level7 = {
            --物理
            "item_chaotic_Claw_of_attack",
            "item_chaotic_blight_stone",
            "item_chaotic_possessed_mask",
            "item_chaotic_broadsword",
            "item_chaotic_blitz_knuckles",
            --法师
            "item_chaotic_keen_optic",
            "item_chaotic_amulet",
            "item_chaotic_mysterious_hat",
            "item_chaotic_sobi_mask",
            --坦克
            "item_chaotic_bogduggs_baldric",
            "item_chaotic_chipped_vest",
            --召唤
            "item_chaotic_shaman_skull",
            "item_chaotic_shaman_necklace",
            --辅助
            "item_chaotic_nian_flag_trap",
            --特殊
            "item_chaotic_energy_ring",
            "item_chaotic_arcane_ring",
            "item_chaotic_circlet",
        },
    },
    --法术攻击性装备
    magical_weapon = {
        level1 = {
            -- "item_hd_voodoo_mask",
            "item_hd_sobi_mask",
            "item_hd_mysterious_hat",
            "item_hd_keen_optic",
            "item_hd_mantle",
            "item_hd_amulet",
            "item_hd_magic_hand",
            "item_hd_shaman_skull",
            "item_hd_shaman_necklace",
            "item_hd_a_stick",

            

        },
        level2 = {
            "item_hd_staff_of_wizardry",
            "item_hd_oblivion_staff",
            "item_hd_tranquil_boots",
            "item_hd_nether_shawl",
            "item_hd_arcane_bow",
            "item_hd_vambrace_int",
            "item_hd_Kaya",
            "item_hd_secret_of_summon",
            "item_hd_soul_of_orc",
            "item_hd_arcane_hat",

        },
        level3 = {
            "item_hd_ring_of_flowing_wind",
            "item_hd_maelstrom",
            "item_hd_orchid",
            "item_hd_star_calling_cloak",
            "item_hd_deathly_scepter",
            "item_hd_enchanted_quiver",
            "item_hd_psychic_headband",
            "item_hd_cyclone_2",
            "item_hd_soul_of_balnock",
            "item_hd_balnocks_furnace",
            "item_hd_mystic_staff",

        },
        level4 = {
            "item_hd_timeless_relic",
            "item_hd_spell_prism",
            "item_hd_minotaur_horn",
            "item_hd_Yasha_and_Kaya",
            "item_hd_tranquil_boots_2",
            "item_hd_Kaya_and_Sange",
            "item_hd_stormcrafter",
            "item_hd_moonrift_longbow",
            "item_hd_wolf_king_mask",
            "item_hd_Siltbreaker_Stonework_Pendant",
            "item_hd_witchbane",
            "item_hd_eye_of_the_vizier",
            "item_hd_poison_fog",
            

        },
        level5 = {
            "item_hd_bloodthorn_magic",
            "item_octarine_core_level3",
            "item_hd_the_secret_of_light",
            "item_hd_seer_stone",
            "item_hd_antarctic_star_spear",
            "item_hd_verodicias_rune_staff",
            "item_hd_bloodstone",
            "item_hd_wind_waker",
            "item_hd_philosopher_stone",
            "item_hd_moirai_hat",
            "item_hd_book_of_death",
            "item_hd_ancient_gemstone",
            "item_hd_potion_of_planar",
            "item_hd_thunder",
            "item_hd_int_ring",
            "item_hd_cloak_of_endless_carnage",
            "item_hd_obliterating_orb",
            "item_hd_hero_cape",
            "item_hd_rose_scepter",
            "item_hd_helm_of_the_overlord",
            "item_hd_shivas_staff",
            "item_hd_argo_paw",
            "item_hd_rule_breaker",
            "item_hd_poison_lokustra",
            "item_hd_outworld_staff",
        },
        --6级物品一般不由过关奖励产生
        level6 = {
            "item_hd_Song_of_Eagle_Voice_of_Dragonus",
        },

        level7 = {
            --物理
            "item_chaotic_blade_of_alacrity",
            "item_chaotic_phase_boots",
            "item_chaotic_Yasha",
            
            "item_chaotic_quicksilver_amulet",
            "item_chaotic_medallion_of_courage",
            "item_chaotic_jack_the_rippers_claw",
            "item_chaotic_anger_coat",
            "item_chaotic_javelin",
            "item_chaotic_pheromone",
            --法师
            "item_chaotic_staff_of_wizardry",
            "item_chaotic_tranquil_boots",
            "item_chaotic_nether_shawl",
            "item_chaotic_Kaya",
            "item_chaotic_soul_of_orc",
            "item_chaotic_arcane_hat",
            "item_chaotic_arcane_boots",
            --坦克
            "item_chaotic_power_treads",
            "item_chaotic_dragon_scale",
            "item_chaotic_sange",
            "item_chaotic_vanguard",
            "item_chaotic_demons_heart_02",
            "item_chaotic_vitality_booster",
            "item_chaotic_Ice_coat",
            "item_chaotic_hood_of_defiance",
            --召唤
            "item_chaotic_secret_of_summon",
            --辅助
            --特殊
            "item_chaotic_vambrace",
            "item_chaotic_shadow_amulet",
            "item_chaotic_precious_egg",
            "item_chaotic_book_of_torture",
            
        },

    },
    --防御性装备
    armor = {
        level1 = {
            "item_hd_ring_of_protection",
            "item_hd_chainmail",
            "item_hd_cloak",
            "item_hd_poor_mans_shield",
            "item_hd_chipped_vest",
            "item_hd_goblin_leather",
            "item_hd_bristleback_single",
            "item_hd_demons_heart_01",
            "item_hd_vengeances_shadow",
            -- "item_hd_slakes_scales",
            "item_hd_gauntlets",
        },
        level2 = {
            "item_hd_ogre_axe",
            "item_hd_power_treads",
            "item_hd_dragon_scale",
            "item_hd_vambrace_str",
            "item_hd_sange",
            "item_hd_hood_of_defiance",
            "item_hd_vanguard",
            "item_hd_demons_heart_02",
            "item_hd_vitality_booster",
            "item_hd_lizard_armor_small",
            -- "item_hd_poison_coat",

        },
        level3 = {
            "item_hd_glimmer_cape",
            "item_hd_blade_mail",
            "item_hd_valhalla_helmet",
            "item_hd_holy_cross_amulet",
            "item_hd_titan_sliver",
            "item_hd_cloak_of_flames",
            -- "item_hd_helm_of_the_undying",
            "item_hd_craggy_coat",
            "item_hd_balnock_shield",
            "item_hd_reaver",

         

        },
        level4 = {
            "item_hd_trickster_cloak",
            "item_hd_Sange_and_Yasha",
            "item_hd_heavens_halberd",
            "item_hero_carapace_of_qaldin",
            "item_hd_eternal_shroud",
            "item_hd_power_treads_2",
            "item_hd_breath_of_life",
            "item_hd_Siltbreaker_Guardian_Shel",
            "item_hd_panic_button",
            -- "item_hd_combo_breaker",
            "item_hd_crimson_guard",
            "item_hd_poison_ball",

        },
        level5 = {
            "item_hd_titan_stone",
            "item_hd_shivas_guard",
            "item_hd_ex_machina",
            "item_hd_giants_ring",
            "item_hd_heart",
            "item_hd_assault",
            "item_hd_radiance",
            "item_hd_remnant_spirit_of_the_ancient_tree",
            "item_hd_witless_shako",
            "item_hd_Siltbreaker_Glimmerdark_Shield",
            "item_hd_Harlequin_green_hat",
            "item_hd_str_ring",
            "item_hd_viigil_signet",
            "item_hd_remnant_sun_prison_garb",
            "item_hd_shield_of_aquila",
            "item_hd_claszureme_hourglass",
            "item_hd_seraphim_shield",
            "item_hd_ristul_emblem",
            "item_hd_demagicking_maul",
            "item_hd_kraken_shell_armor",
            "item_hd_siltbreaker_rhyzik_eye",
            "item_hd_brain_worm",
            "item_hd_helm_of_disjunction",
            "item_hd_horn_of_winter",
            "item_hd_mythrienss_ring",
            "item_hd_font_of_time",
            "item_hd_shield_of_the_hidden_lord_1",
            "item_hd_starry_sky_dome",
            "item_hd_defiant_shell",
            "item_hd_modular_armor",
            "item_hd_blood_bug_barrier",
        },
        --6级物品一般不由过关奖励产生
        level6 = {

        },

        level7 = {
        },

    },
    --辅助性装备
    subsidiarity = {
        level1 = {
            "item_hd_magic_stick",
            -- "item_hd_mango_tree",
            "item_hd_ocean_heart",
            "item_hd_energy_ring",
            "item_hd_arcane_ring",
            "item_hd_anti_energy_ring",
            "item_hd_anti_arcane_ring",
            "item_hd_nian_flag_trap",
            "item_hd_creed_of_omniscience",
            "item_hd_buckler_active",
            
        },
        level2 = {
            "item_hd_magic_wand",
            "item_hd_arcane_boots",
            "item_hd_ring_of_aquila_active",
            "item_hd_bullwhip",
            "item_hd_mekansm",
            "item_hd_curse_staff",
            "item_hd_qingnan_sheet",
            "item_hd_pheromone",
            "item_hd_Ice_coat",
            -- "item_hd_SilenceDarkness",
            -- "item_hd_sparkle",
            

        },
        level3 = {
            "item_hd_vladmir",
            "item_hd_holy_locket",
            -- "item_hd_anti_energy_ring_2",
            "item_hd_energy_ring_2",
            "item_hd_arcane_ring_2",
            -- "item_hd_anti_arcane_ring_2",
            "item_hd_ceremonial_robe",
            "item_hd_force_staff",
            "item_hd_ring_of_aquila",
            "item_hd_slave_owners_flame_whip",

        },
        level4 = {
            "item_hd_spy_gadget",
            "item_hd_arcane_boots_2",
            "item_hd_holy_cross_cloak",
            "item_hd_holy_cross_battlefield",
            "item_hd_holy_cross_hand_guard",
            "item_hd_Siltbreaker_Ambient_Sorcery",
            "item_hd_sheepstick",
            "item_hd_grandmasters_glaive",
            "item_hd_Siltbreaker_Watcher_Gaze",
            "item_hd_Siltbreaker_Preserved_Skull",

        },
        level5 = {
            "item_hd_lamb_divine_staff",
            "item_hd_saurian_fasciculus",
            "item_hd_ice_blossom",
            "item_hd_yulsarias_glacier",
            "item_hd_alluvion_prophecy",
            "item_hd_sagas_of_the_cymurrin_sage",
            "item_hd_yulsarias_mantle",
            "item_hd_paragons_rebuke",
            "item_hd_fetters_of_omniscience",
            "item_hd_ice_ring",
            "item_hd_fate_ring",
            "item_hd_witch_crown",
            "item_hd_rumusque_vestments",
            "item_hd_high_priest_robe",
            "item_hd_tears_of_aquastar",
            "item_hd_wingfall_hammer",
            "item_hd_tome_of_living_memories1",
            "item_hd_helm_of_omni",
            "item_hd_scarecrow_hat",
            "item_hd_broken_promise",
            
        },
        --6级物品一般不由过关奖励产生
        level6 = {
            "item_hd_tome_of_living_memories2",
            "item_hd_vladmir_2",
            "item_hd_flower_locket",
        },

        level7 = {
        },

    },
    --特殊
    special = {
        level1 = {
            -- "item_hd_courier_radiant",
            "item_hd_faded_broach",
            "item_hd_dust",
            "item_hd_BountyHunters_gold_bag",
            "item_hd_gold_bag",
            "item_hd_royal_jelly2",
            "item_hd_boots",
            "item_hd_soul_1",
            "item_hd_mad_potion",
            "item_hd_pool_blink",
            "item_hd_creed_of_omniscience_2",
            "item_hd_madstone_bundle",
           

        },
        level2 = {
            "item_hd_star_mace",
            "item_hd_shadow_amulet",
            "item_hd_travel_boots",
            "item_hd_philosophers_stone",
            "item_hd_pupils_gift",
            "item_hd_precious_egg",
            -- "item_hd_skeletology",
            "item_hd_expired_meat",
            "item_hd_evil_coat",
            "item_hd_book_of_torture",
            "item_hd_occult_bracelet",
        },
        level3 = {
            "item_hd_soul_booster",
            -- "item_hd_advanced_mathematics",
            -- "item_hd_introduction_of_arcane",
            -- "item_hd_advanced_mathematics",
            "item_hd_quickening_charm",
            "item_hd_spider_legs",
            "item_hd_risk_dice",
            "item_hd_shield_of_lackeys",
            "item_hd_staff_of_lackeys",
            "item_hd_bottle_water",
            "item_hd_ultimate_orb",
            "item_secret_of_experience"	,
            "item_hd_soul_2",
            "item_hd_dust2",
            "item_hd_revtel_signet_ring",
            "item_hd_blink",
            "item_hd_guardian_ring",
            "item_hd_point_booster",

        },
        level4 = {
            "item_hd_flicker",
            "item_hd_travel_boots_lv2",
            "item_hd_hunters_hoard",
            "item_hd_secret_of_time",
            -- "item_hd_neutral",
            "item_hd_Siltbreaker_Unhallowed",
            -- "item_hd_black_king_bar",
            "item_hd_sphere",
            -- "item_hd_valhalla_helmet",
            "item_hd_moon_shard",
            "item_secret_of_experience",
            "item_hd_arcana_blink",
            "item_hd_aghanims_shard",
            "item_hd_bottle_invisibility",
            "item_hd_lotus_orb",
            "item_hd_enhancement_wise",

        },
        level5 = {
            "item_hd_force_boots",
            "item_hd_mirror_shield",
            "item_hd_apex",
            "item_hd_fallen_sky",
            "item_hd_pirate_hat",
            "item_hd_trident",
            "item_hd_ancient_living_stone",
            "item_Blessing_of_the_Chanter",
            "item_secret_of_experience",	
            "item_hd_eden_blacksmith",
            "item_hd_hermes_boots",
            "item_hd_galaxy_compass",
            "item_hd_rubick_cube",
            "item_hd_rubick_cube2",
            "item_hd_phoenix_ring",
            "item_hd_book_of_death_2",
            "item_hd_advanced_keen_optic",
            "item_hd_bogduggs_lucky_femur",
            "item_hd_ultimate_scepter",
            "item_hd_selecter_terminal",
            "item_hd_bottledthundertorm",
            "item_hd_chrono_casket",
            "item_hd_flash_change_brooch",
            "item_hd_thousand_leagues_astrologer",
            "item_hd_modular_boots",
            "item_hd_revenants_brooch_player",
            "item_hd_iron_part",
            "item_hd_third_eye",
            "item_hd_travel_boots_tinker",
            "item_hd_dandelion_amulet",
            "item_hd_refresher",

        },
        --6级物品一般不由过关奖励产生
        level6 = {
            "item_hd_mul_ring",
        },

        level7 = {
            --物理
            "item_chaotic_sword_of_seven",
            "item_chaotic_critdrow",
            "item_chaotic_ballista",
            "item_chaotic_butterfly",
            --法师
            "item_chaotic_dagon",
            "item_chaotic_dezun_bloodrite",
            "item_chaotic_devastator",
            --坦克
            "item_chaotic_unrelenting_eye",
            "item_chaotic_roshan_heart",
            "item_chaotic_glimmerdark_shield",
            --召唤
            "item_chaotic_necronomicon_1",
            "item_chaotic_necronomicon_2",
            "item_chaotic_necronomicon_3",
            --辅助
            "item_chaotic_roshan_flag_defense",
            "item_chaotic_roshan_flag_attack",
            "item_chaotic_roshan_flag_cooldown",
            "item_chaotic_roshan_flag_final",
            --独特
            "item_chaotic_proficstaff",
            "item_chaotic_crown", 
            "item_chaotic_crown_alter",
            "item_chaotic_element_stone",
            "item_chaotic_blink_str",
            "item_chaotic_blink_agi",
            "item_chaotic_blink_int",
        },
    },

}