"KeyValue"
{
	"chaotic_ice_age"
	{
		"class_level"							"10"
		"weight"								"100"
		"level1"								"1"
		"level2"								"1"
		"level3"								"1"
		"level4"								"1"
		"level5"								"0"
		"ImmortalStyleCount"					"0"
		"level6"								"0"
		"ArcanaStyleCount"						"0"
	}
	"chaotic_sky_fire"
	{
		"class_level"							"10"
		"weight"								"100"
		"level1"								"1"
		"level2"								"1"
		"level3"								"1"
		"level4"								"1"
		"level5"								"0"
		"ImmortalStyleCount"					"0"
		"level6"								"0"
		"ArcanaStyleCount"						"0"
	}
	"chaotic_Thundergods_Wrath"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_deafening_blast"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_Coup_De_Grace"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_summon_sprite_king"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_black_hole"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_frost_arrows"
	{
		"class_level"							"10"
		"weight"								"100"
	}
	"chaotic_tri_comet"
	{
		"class_level"							"10"
		"weight"								"150"
	}
}
