"KeyValue"
{
	"chaotic_elemental_weapon"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_haste"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_lightning_bolt"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_mass_healing_word"
	{
		"class_level"							"3"
		"weight"								"300"
	}
	"chaotic_plant_growth"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_conjure_barrage"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_hunger_of_hadar"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_beacon_of_hope"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_parasitic_fantasy_poison"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_immediate_reflex"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_fire_ball"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_protection_from_energy"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_weapon_enchantment"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_magic_emanation"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_weakness_perception"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_area"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_pierce"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_summon_wild_bear"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_communication_among_living_beings"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_soul_transfer"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_liquid_frost"
	{
		"class_level"							"3"
		"weight"								"100"
	}
	"chaotic_warlord_fever"
	{
		"class_level"							"3"
		"weight"								"100"
	}
}
