"KeyValue"
{
	"Chaotic_Era_max_monster"
	{
		"value"									"65"
	}
	"Chaotic_Era_Game_Fail_coutDown"
	{
		"value"									"10"
	}
	"Chaotic_Era_bonus_monster_per_player"
	{
		"value"									"0"
	}
	"Chaotic_Era_bonus_monster_general_rate"
	{
		"value"									"0"
	}
	"Chaotic_Era_monster_spawn_delay"
	{
		"value"									"4"
	}
	"Chaotic_Era_Spell_Require_Index"
	{
		"value"									"0.6"
	}
	"Rune_Progress_PlayerCountIndex"
	{
		"value1"								"1"
		"value2"								"1"
		"value3"								"1"
		"value4"								"1"
		"value5"								"1"
	}
	"Rune_Progress_Base_Require"
	{
		"value"									"1"
	}
	"Rune_Progress_Base_Require_Pow"
	{
		"value"									"1.1"
	}
	"Chaotic_Era_Task_Count"
	{
		"value"									"4"
	}
	"Chaotic_Era_Task_Time_Require"
	{
		"value"									"10"
	}
	"Chaotic_Era_GetTalentRound"
	{
		"value"									"7"
	}
	"Chaotic_Era_Shop_ExpRequire"
	{
		"value1"								"2"
		"value2"								"3"
		"value3"								"4"
		"value4"								"5"
		"value5"								"6"
		"value6"								"7"
		"value7"								"8"
		"value8"								"9"
		"value9"								"10"
	}
	"Chaotic_Era_Shop_UpgradeCost"
	{
		"value"									"1500"
	}
	"Chaotic_Era_Shop_RefreshCost"
	{
		"value"									"300"
	}
	"Chaotic_Era_Shop_RefreshCost_Bonus"
	{
		"value"									"50"
	}
	"Chaotic_Era_Task_RefreshCost"
	{
		"value"									"200"
	}
	"Chaotic_Era_Task_RefreshCost_Bonus"
	{
		"value"									"0"
	}
	"Chaotic_Era_GeneralAbility_GenerateCount"
	{
		"value"									"4"
	}
	"Chaotic_Era_ChaoticAbility_GenerateCount"
	{
		"value"									"4"
	}
	"Chaotic_Era_InitSpellCount"
	{
		"value"									"2"
	}
	"Chaotic_Era_GeneralSpell_Count_Limit"
	{
		"value"									"9"
	}
	"Chaotic_Era_Buy_Spell_gold_return"
	{
		"value"									"500"
	}
	"Chaotic_Era_Rune_To_Exp"
	{
		"value1"								"20"
		"value2"								"80"
		"value3"								"320"
		"value4"								"1280"
		"value5"								"5120"
	}
	"Chaotic_Era_Rune_To_Aurum"
	{
		"value1"								"0.25"
		"value2"								"1"
		"value3"								"4"
		"value4"								"16"
		"value5"								"64"
	}
	"Chaotic_Era_Shop_Max_Level"
	{
		"value"									"13"
	}
	"Chaotic_Era_Shop_RefreshCount"
	{
		"value1"								"3"
		"value2"								"4"
		"value3"								"5"
		"value4"								"6"
		"value5"								"7"
		"value6"								"8"
		"value7"								"9"
		"value8"								"10"
		"value9"								"10"
		"value10"								"10"
		"value11"								"10"
		"value12"								"10"
		"value13"								"10"
	}
	"Chaotic_Era_Shop_Level_1"
	{
		"value1"								"100"
		"value2"								"0"
		"value3"								"0"
		"value4"								"0"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_2"
	{
		"value1"								"90"
		"value2"								"10"
		"value3"								"0"
		"value4"								"0"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_3"
	{
		"value1"								"80"
		"value2"								"20"
		"value3"								"0"
		"value4"								"0"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_4"
	{
		"value1"								"70"
		"value2"								"25"
		"value3"								"5"
		"value4"								"0"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_5"
	{
		"value1"								"60"
		"value2"								"30"
		"value3"								"10"
		"value4"								"0"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_6"
	{
		"value1"								"50"
		"value2"								"30"
		"value3"								"15"
		"value4"								"5"
		"value5"								"0"
	}
	"Chaotic_Era_Shop_Level_7"
	{
		"value1"								"35"
		"value2"								"35"
		"value3"								"15"
		"value4"								"10"
		"value5"								"5"
	}
	"Chaotic_Era_Shop_Level_8"
	{
		"value1"								"20"
		"value2"								"30"
		"value3"								"25"
		"value4"								"18"
		"value5"								"12"
	}
	"Chaotic_Era_Shop_Level_9"
	{
		"value1"								"5"
		"value2"								"15"
		"value3"								"30"
		"value4"								"30"
		"value5"								"20"
	}
	"Chaotic_Era_Shop_Level_10"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"25"
		"value4"								"40"
		"value5"								"35"
	}
	"Chaotic_Era_Shop_Level_11"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"10"
		"value4"								"30"
		"value5"								"60"
	}
	"Chaotic_Era_Shop_Level_12"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"20"
		"value5"								"80"
	}
	"Chaotic_Era_Shop_Level_13"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"0"
		"value5"								"100"
	}
	"Chaotic_Era_Spell_Level_1"
	{
		"value1"								"100"
		"value2"								"0"
		"value3"								"0"
		"value4"								"0"
		"value5"								"0"
		"value6"								"0"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_2"
	{
		"value1"								"90"
		"value2"								"10"
		"value3"								"0"
		"value4"								"0"
		"value5"								"0"
		"value6"								"0"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_3"
	{
		"value1"								"70"
		"value2"								"20"
		"value3"								"10"
		"value4"								"0"
		"value5"								"0"
		"value6"								"0"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_4"
	{
		"value1"								"40"
		"value2"								"30"
		"value3"								"20"
		"value4"								"10"
		"value5"								"0"
		"value6"								"0"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_5"
	{
		"value1"								"20"
		"value2"								"30"
		"value3"								"20"
		"value4"								"20"
		"value5"								"10"
		"value6"								"0"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_6"
	{
		"value1"								"0"
		"value2"								"20"
		"value3"								"30"
		"value4"								"30"
		"value5"								"10"
		"value6"								"10"
		"value7"								"0"
		"value8"								"0"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_7"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"20"
		"value4"								"25"
		"value5"								"20"
		"value6"								"20"
		"value7"								"10"
		"value8"								"5"
		"value9"								"0"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_8"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"10"
		"value5"								"20"
		"value6"								"20"
		"value7"								"20"
		"value8"								"15"
		"value9"								"10"
		"value10"								"5"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_9"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"5"
		"value5"								"10"
		"value6"								"15"
		"value7"								"15"
		"value8"								"20"
		"value9"								"25"
		"value10"								"10"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_10"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"5"
		"value5"								"5"
		"value6"								"15"
		"value7"								"15"
		"value8"								"20"
		"value9"								"25"
		"value10"								"15"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_11"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"5"
		"value5"								"5"
		"value6"								"10"
		"value7"								"15"
		"value8"								"20"
		"value9"								"25"
		"value10"								"20"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_12"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"5"
		"value5"								"5"
		"value6"								"5"
		"value7"								"10"
		"value8"								"15"
		"value9"								"20"
		"value10"								"40"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_Level_13"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"5"
		"value5"								"5"
		"value6"								"5"
		"value7"								"5"
		"value8"								"10"
		"value9"								"15"
		"value10"								"55"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_GeneralSpell_Evolution"
	{
		"value1"								"5"
		"value2"								"8"
		"value3"								"11"
		"value4"								"14"
		"value5"								"17"
		"value6"								"20"
		"value7"								"23"
		"value8"								"26"
		"value9"								"29"
		"value10"								"31"
		"value11"								"34"
		"value12"								"37"
		"value13"								"40"
	}
	"Chaotic_Era_Spell_GeneralSpell_Evolution_OnUpgradeShop"
	{
		"value1"								"0"
		"value2"								"0"
		"value3"								"0"
		"value4"								"1"
		"value5"								"0"
		"value6"								"0"
		"value7"								"1"
		"value8"								"0"
		"value9"								"1"
		"value10"								"0"
		"value11"								"0"
		"value12"								"0"
		"value13"								"0"
	}
	"Chaotic_Era_Spell_GeneralSpell_Upgrade"
	{
		"value1"								"10"
		"value2"								"20"
		"value3"								"30"
		"value4"								"40"
		"value5"								"50"
		"value6"								"60"
		"value7"								"70"
		"value8"								"80"
		"value9"								"90"
		"value10"								"100"
		"value11"								"100"
		"value12"								"100"
		"value13"								"100"
	}
	"Chaotic_Era_Spell_GeneralSpell_Sell"
	{
		"value1"								"5"
		"value2"								"10"
		"value3"								"15"
		"value4"								"20"
		"value5"								"23"
		"value6"								"26"
		"value7"								"29"
		"value8"								"32"
		"value9"								"35"
		"value10"								"38"
		"value11"								"45"
		"value12"								"55"
		"value13"								"70"
	}
	"Chaotic_Era_Spell_SpellBuyChance"
	{
		"value"									"100"
	}
	"Chaotic_Era_RefreshTask"
	{
		"value1"								"100"
		"value2"								"100"
		"value3"								"100"
		"value4"								"100"
		"value5"								"100"
		"value6"								"100"
		"value7"								"100"
		"value8"								"100"
		"value9"								"100"
		"value10"								"100"
		"value11"								"100"
		"value12"								"100"
		"value13"								"100"
	}
	"Chaotic_era_PotionCount"
	{
		"value1"								"2"
		"value2"								"2"
		"value3"								"2"
		"value4"								"2"
		"value5"								"3"
		"value6"								"3"
		"value7"								"3"
		"value8"								"4"
		"value9"								"4"
		"value10"								"4"
		"value11"								"4"
		"value12"								"4"
		"value13"								"4"
	}
	"Chaotic_Era_Spell_Artifact"
	{
		"value1"								"0"
		"value2"								"23"
		"value3"								"26"
		"value4"								"29"
		"value5"								"32"
		"value6"								"35"
		"value7"								"40"
		"value8"								"50"
		"value9"								"60"
		"value10"								"70"
		"value11"								"75"
		"value12"								"80"
		"value13"								"85"
	}
	"Chaotic_Era_Spell_GeneralSpell_Evolution_max_charge"
	{
		"value"									"4"
	}
	"Chaotic_Era_Spell_GeneralSpell_Upgrade_max_charge"
	{
		"value"									"24"
	}
	"Chaotic_Era_Spell_GeneralSpell_Sell_max_charge"
	{
		"value"									"5"
	}
	"Chaotic_Era_Spell_GeneralSpell_SpellChance_max_charge"
	{
		"value"									"3"
	}
	"Chaotic_Era_RefreshTask_max_charge"
	{
		"value"									"10"
	}
	"Chaotic_Era_Item_Lock_Max"
	{
		"value"									"4"
	}
	"Chaotic_Era_Init_Sell_Charge"
	{
		"value"									"2"
	}
	"Chaotic_Era_Init_Buy_Charge"
	{
		"value"									"0"
	}
	"Chaotic_Era_Init_Evolution_Charge"
	{
		"value"									"1"
	}
	"Chaotic_Era_Init_Spell_Artifact_Charge"
	{
		"value"									"1"
	}
	"Chaotic_Era_Spell_Artifact_max_charge"
	{
		"value"									"3"
	}
	"Chaotic_Era_Spell_GeneralSpell_Evolution_cost"
	{
		"value"									"1500"
		"value1"								"400"
	}
	"Chaotic_Era_Spell_GeneralSpell_Upgrade_cost"
	{
		"value"									"500"
		"value1"								"0"
	}
	"Chaotic_Era_Spell_GeneralSpell_Sell_cost"
	{
		"value"									"250"
		"value1"								"0"
	}
	"Chaotic_Era_Spell_GeneralSpell_SpellChance_cost"
	{
		"value"									"500"
		"value1"								"500"
		"value2"								"500"
	}
	"Chaotic_Era_Spell_GeneralSpell_Artifact_cost"
	{
		"value"									"0"
		"value1"								"1600"
	}
	"Chaotic_Era_Stop_TaskGenetate_LevelRequire"
	{
		"value"									"1"
	}
	"Chaotic_Era_Stop_TaskGenetate_Time"
	{
		"value"									"30"
	}
	"Chaotic_Era_Stop_TaskGenetate_CooldownTime"
	{
		"value"									"240"
	}
	"Chaotic_Era_Stop_TaskGenetate_Cost"
	{
		"value"									"0"
	}
	"Rune_Del_return_1"
	{
		"value1"								"10"
		"value2"								"0.25"
		"value5"								"100"
		"value6"								"1"
	}
	"Rune_Del_return_2"
	{
		"value1"								"50"
		"value2"								"1"
		"value5"								"400"
		"value6"								"4"
	}
	"Rune_Del_return_3"
	{
		"value1"								"250"
		"value2"								"4"
		"value5"								"1600"
		"value6"								"16"
	}
	"Rune_Del_return_4"
	{
		"value1"								"1250"
		"value2"								"16"
		"value5"								"6400"
		"value6"								"64"
	}
	"Rune_Del_return_5"
	{
		"value1"								"6250"
		"value2"								"64"
		"value5"								"25600"
		"value6"								"256"
	}
	"Rune_Del_return_6"
	{
		"value1"								"31250"
		"value2"								"256"
		"value5"								"102400"
		"value6"								"1024"
	}
	"freeReRollAbility"
	{
		"value"									"2"
	}
	"rerollAbilityCharge"
	{
		"value"									"5"
	}
	"rerollAurumCost"
	{
		"value"									"10"
	}
	"Talent_count"
	{
		"value"									"5"
	}
	"hero_talent_weight"
	{
		"value"									"1000"
	}
	"Chaotic_Era_upgrade_attribute"
	{
		"value"									"200"
	}
	"Chaotic_Era_upgrade_progress"
	{
		"value"									"100"
	}
	"Chaotic_era_primary_map_effect_count"
	{
		"value"									"5"
	}
	"Chaotic_era_middle_map_effect_count"
	{
		"value"									"4"
	}
	"Chaotic_era_advanced_map_effect_count"
	{
		"value"									"4"
	}
	"Chaotic_era_middle_map_effect_round"
	{
		"value"									"10"
	}
	"Chaotic_era_advanced_map_effect_round"
	{
		"value"									"20"
	}
	"Chaotic_era_success_bonus_index"
	{
		"value"									"10"
	}
	"Chaotic_era_artifact_genetate_count"
	{
		"value"									"3"
	}
	"Chaotic_Era_Final_Wave"
	{
		"value"									"35"
	}
	"Chaotic_Era_Weak_Time"
	{
		"value"									"180"
	}
	"Chaotic_Era_Bonus_Attribute_Count"
	{
		"value"									"15"
	}
	"Bonus_artifact_wave"
	{
		"value1"								"10"
		"value2"								"20"
		"value3"								"22"
		"value4"								"27"
	}
	"player_artifact_exp_bonus_wave"
	{
		"value"									"9"
		"value1"								"1.06"
	}
	"Chaotic_Era_Rune_To_ArtifactExp"
	{
		"value"									"0.8"
	}
	"Staging_exp_pct"
	{
		"value"									"40"
	}
	"Drop_ArtifactChance_RuneUpgrade"
	{
		"value1"								"0.15"
		"value2"								"0.5"
		"value3"								"1.1"
		"value4"								"3"
		"value5"								"16"
		"value6"								"35"
	}
}
